name: restore-hermes-workspace
description: "Restore hermes workspace that has been created in Prepare Hermes Workspace"
runs:
  using: composite
  steps:
    - name: Download Previous Artifacts
      uses: actions/download-artifact@v4
      with:
        name: hermes-workspace
        path: /tmp/hermes
    - name: Set up workspace
      shell: bash
      run: |
        mkdir -p $HERMES_OSXBIN_ARTIFACTS_DIR ./packages/react-native/sdks/hermes
        cp -r $HERMES_WS_DIR/hermes/* ./packages/react-native/sdks/hermes/.
        cp -r ./packages/react-native/sdks/hermes-engine/utils ./packages/react-native/sdks/hermes/.
