include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'toolbar',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_target('java/com/facebook/csslayout:csslayout'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    '//libraries/imagepipeline/src/main/java/com/facebook/imagepipeline/bitmaps:bitmaps',
    '//libraries/imagepipeline/src/main/java/com/facebook/imagepipeline/common:common',
    '//libraries/imagepipeline/src/main/java/com/facebook/imagepipeline/request:request',
    '//libraries/imagepipeline/src/main/java/com/facebook/imagepipeline/image:image',
    '//libraries/drawee/src/main/java/com/facebook/drawee/controller:controller',
    '//libraries/drawee/src/main/java/com/facebook/drawee/drawable:drawable',
    '//libraries/drawee/src/main/java/com/facebook/drawee/generic:generic',
    '//libraries/drawee/src/main/java/com/facebook/drawee/interfaces:interfaces',
    '//libraries/drawee/src/main/java/com/facebook/drawee/view:view',
    '//libraries/fresco/drawee-backends/drawee-pipeline/src/main/java/com/facebook/drawee/backends/pipeline:pipeline',
    '//third-party/android-support-for-standalone-apps/v7/appcompat:appcompat-23.1',
    '//third-party/android-support-for-standalone-apps/v7/appcompat:res-for-react-native',
    '//third-party/java/android/support/v4:lib-support-v4',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':toolbar',
)
