include_defs("//ReactAndroid/DEFS")

android_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)
