name: Yarn
description: Runs `yarn install`
inputs:
  immutable:
    description: Abort with an error exit code if the lockfile was to be modified
    default: true
runs:
  using: composite
  steps:
    - name: Install npm dependencies
      if: ${{ inputs.immutable == 'true' }}
      run: yarn
      shell: bash
    - name: Install npm dependencies (ignore lockfile changes)
      if: ${{ inputs.immutable != 'true' }}
      run: yarn --no-immutable
      shell: bash
