# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep")

java_library(
    name = "robolectric",
    srcs = [],
    resources = [
        "robolectric.properties",
    ],
    resources_root = ".",
    visibility = ["PUBLIC"],
    exported_deps = [
        react_native_dep("third-party/java/robolectric/4.4:robolectric"),
    ],
)
