load("@fbsource//tools/build_defs/apple:autoglob.bzl", "EXPORT_UNLESS_INTERNAL")
load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library")

fb_apple_library(
    name = "RCTRequired",
    autoglob = True,
    autoglob_mode = EXPORT_UNLESS_INTERNAL,
    complete_nullability = True,
    contacts = ["oncall+react_native@xmail.facebook.com"],
    extension_api_only = True,
    frameworks = ["Foundation"],
    labels = ["supermodule:xplat/default/public.react_native.infra"],
)
