load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library")

fb_apple_library(
    name = "RCTRequired",
    autoglob = True,
    contacts = ["oncall+react_native@xmail.facebook.com"],
    frameworks = ["Foundation"],
    labels = ["supermodule:ios/isolation/infra.react_native"],
)
