load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library")

fb_apple_library(
    name = "RCTRequired",
    exported_headers = [
        "RCTRequired/RCTRequired.h",
    ],
    autoglob = False,
    complete_nullability = True,
    contacts = ["oncall+react_native@xmail.facebook.com"],
    extension_api_only = True,
    frameworks = ["Foundation"],
    labels = [
        "fbios_link_group:xplat/default/public.react_native.infra",
        "pfh:ReactNative_CommonInfrastructurePlaceholder",
        "talkios_link_group:xplat/default/public.react_native.infra",
    ],
)
