include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'testing',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
    react_native_dep('third-party/android/support/v4:lib-support-v4'),
    react_native_dep('third-party/java/infer-annotations:infer-annotations'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    react_native_dep('third-party/java/junit:junit'),
    react_native_dep('third-party/java/mockito:mockito'),
    react_native_dep('third-party/java/testing-support-lib:runner'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/devsupport:devsupport'),
    react_native_target('java/com/facebook/react/modules/core:core'),
    react_native_target('java/com/facebook/react/modules/debug:debug'),
    react_native_target('java/com/facebook/react/shell:shell'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_target('java/com/facebook/react:react'),
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':testing',
)
