load("//ReactNative:DEFS.bzl", "rn_android_library", "react_native_dep", "react_native_integration_tests_target", "react_native_target")

rn_android_library(
    name = "testing",
    srcs = glob(
        ["**/*.java"],
        excludes = [
            "idledetection/**/*.java",
            "network/**/*.java",
        ],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/java/buck-android-support:buck-android-support"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/junit:junit"),
        react_native_dep("third-party/java/mockito:mockito"),
        react_native_dep("third-party/java/testing-support-lib:runner"),
        react_native_integration_tests_target("java/com/facebook/react/testing/idledetection:idledetection"),
        react_native_integration_tests_target("java/com/facebook/react/testing/network:network"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/devsupport:interfaces"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
        react_native_target("java/com/facebook/react/module/model:model"),
        react_native_target("java/com/facebook/react/modules/core:core"),
        react_native_target("java/com/facebook/react/modules/debug:interfaces"),
        react_native_target("java/com/facebook/react/shell:shell"),
        react_native_target("java/com/facebook/react/uimanager:uimanager"),
        react_native_target("res:uimanager"),
    ],
)
