load("//ReactNative:DEFS.bzl", "ANDROID", "ANDROID_JSC_INTERNAL_DEPS", "APPLE", "APPLE_JSC_INTERNAL_DEPS", "react_native_xplat_target", "rn_xplat_cxx_library")

EXPORTED_HEADERS = [
    "JavaScriptCore.h",
    "JSCHelpers.h",
    "JSCWrapper.h",
    "noncopyable.h",
    "Unicode.h",
    "Value.h",
]

rn_xplat_cxx_library(
    name = "jscinternalhelpers",
    srcs = glob(
        ["*.cpp"],
        exclude = ["systemJSCWrapper.cpp"],
    ),
    headers = glob(
        ["*.h"],
        exclude = EXPORTED_HEADERS,
    ),
    header_namespace = "",
    exported_headers = dict([
        (
            "jschelpers/%s" % header,
            header,
        )
        for header in EXPORTED_HEADERS
    ]),
    compiler_flags = [
        "-Wall",
        "-fexceptions",
        "-frtti",
        "-fvisibility=hidden",
        "-std=c++1y",
    ],
    fbandroid_deps = ANDROID_JSC_INTERNAL_DEPS,
    fbobjc_deps = APPLE_JSC_INTERNAL_DEPS,
    force_static = True,
    platforms = (ANDROID, APPLE),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "xplat//folly:molly",
        "xplat//third-party/glog:glog",
        react_native_xplat_target("privatedata:privatedata"),
    ],
    exported_deps = [
        react_native_xplat_target("privatedata:privatedata"),
    ],
)

rn_xplat_cxx_library(
    name = "jschelpers",
    srcs = [],
    compiler_flags = [
        "-Wall",
        "-fexceptions",
        "-fvisibility=hidden",
        "-std=c++1y",
    ],
    fbobjc_frameworks = [
        "$SDKROOT/System/Library/Frameworks/JavaScriptCore.framework",
    ],
    fbobjc_srcs = ["systemJSCWrapper.cpp"],
    force_static = True,
    platforms = (ANDROID, APPLE),
    visibility = [
        "PUBLIC",
    ],
    deps = [":jscinternalhelpers"],
)
