load("//tools/build_defs/oss:rn_defs.bzl", "rn_android_library", "react_native_dep")

rn_android_library(
    name = "systrace",
    srcs = glob(["*.java"]),
    autoglob = False,
    language = "JAVA",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/android/androidx:tracing"),
    ],
)
