load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "rn_android_library")

rn_android_library(
    name = "systrace",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    provided_deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
    ]
)
