load("//ReactNative:DEFS.bzl", "react_native_dep", "rn_android_resource")

# used by ReactToolbarManager because of Gradle
# TODO t10182713 will be replaced with appcompat-orig when we stop using Gradle
rn_android_resource(
    name = "appcompat",
    package = "com.facebook.react",
    res = react_native_dep("third-party/android/support/v7/appcompat-orig:res-unpacker-cmd"),
    visibility = ["//ReactAndroid/..."],
)
