exclude_patterns:
  - "*/ReactCommon/react/nativemodule/fantomtestspecificmethods/*"
  - "*/test_utils/*"
  - "*/test/*"

platforms:
  ReactCommon:
    codegen:
    inputs:
      - packages/react-native/ReactCommon
    exclude_patterns:
      - "*/jni/*"
      - "*/platform/cxx/*" # Should this be included in ReactCommon?
      - "*/platform/windows/*"
      - "*/platform/macos/*"
      - "*/platform/ios/*"
      - "*/platform/android/*"
    input_filter: false
    definitions:
    variants:
      debug:
        definitions:
          DEBUG: 1
          REACT_NATIVE_DEBUG: 1
      release:
        definitions:
          NDEBUG: 1
          REACT_NATIVE_PRODUCTION: 1
  ReactAndroid:
    codegen:
      platform: android
    inputs:
      - packages/react-native/ReactCommon
      - packages/react-native/ReactAndroid
    exclude_patterns:
      - "*/platform/cxx/*"
      - "*/platform/windows/*"
      - "*/platform/macos/*"
      - "*/platform/ios/*"
    input_filter: false
    definitions:
      RN_SERIALIZABLE_STATE: 1
      ANDROID: 1
    variants:
      debug:
        definitions:
          DEBUG: 1
          REACT_NATIVE_DEBUG: 1
      release:
        definitions:
          NDEBUG: 1
          REACT_NATIVE_PRODUCTION: 1
  # ReactIOS?
  ReactApple:
    codegen:
      platform: ios
    inputs:
      - packages/react-native/ReactCommon
      - packages/react-native/React
      - packages/react-native/ReactApple
      - packages/react-native/Libraries
    exclude_patterns:
      - "*/jni/*"
      - "*/platform/cxx/*"
      - "*/platform/windows/*"
      - "*/platform/macos/*"
      - "*/platform/android/*"
      - "*+Private.h"
      - "*+Internal.h"
      - "*/scripts/*"
      - "*/templates/*"
    input_filter: true
    definitions:
      __cplusplus: 1
    variants:
      debug:
        definitions:
          DEBUG: 1
          REACT_NATIVE_DEBUG: 1
      release:
        definitions:
          NDEBUG: 1
          REACT_NATIVE_PRODUCTION: 1
