name: Setup node.js
description: 'Set up your GitHub Actions workflow with a specific version of node.js'
inputs:
  node-version:
    description: 'The node.js version to use'
    required: false
    default: '20'
runs:
  using: "composite"
  steps:
    - name: corepack enable
      run: corepack enable
      shell: bash
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
