/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

package com.facebook.yoga

public enum class YogaAlign(public val intValue: Int) {
  AUTO(0),
  FLEX_START(1),
  CENTER(2),
  FLEX_END(3),
  STRETCH(4),
  BASELINE(5),
  SPACE_BETWEEN(6),
  SPACE_AROUND(7),
  SPACE_EVENLY(8),
  START(9),
  END(10);

  public fun intValue(): Int = intValue

  public companion object {
    @JvmStatic
    public fun fromInt(value: Int): YogaAlign =
        when (value) {
          0 -> AUTO
          1 -> FLEX_START
          2 -> CENTER
          3 -> FLEX_END
          4 -> STRETCH
          5 -> BASELINE
          6 -> SPACE_BETWEEN
          7 -> SPACE_AROUND
          8 -> SPACE_EVENLY
          9 -> START
          10 -> END
          else -> throw IllegalArgumentException("Unknown enum value: $value")
        }
  }
}
