/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

package com.facebook.yoga

public enum class YogaOverflow(public val intValue: Int) {
  VISIBLE(0),
  HIDDEN(1),
  SCROLL(2);

  public fun intValue(): Int = intValue

  public companion object {
    @JvmStatic
    public fun fromInt(value: Int): YogaOverflow =
        when (value) {
          0 -> VISIBLE
          1 -> HIDDEN
          2 -> SCROLL
          else -> throw IllegalArgumentException("Unknown enum value: $value")
        }
  }
}
