/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

package com.facebook.yoga

public enum class YogaWrap(public val intValue: Int) {
  NO_WRAP(0),
  WRAP(1),
  WRAP_REVERSE(2);

  public fun intValue(): Int = intValue

  public companion object {
    @JvmStatic
    public fun fromInt(value: Int): YogaWrap =
        when (value) {
          0 -> NO_WRAP
          1 -> WRAP
          2 -> WRAP_REVERSE
          else -> throw IllegalArgumentException("Unknown enum value: $value")
        }
  }
}
