/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

package com.facebook.yoga

public enum class YogaNodeType(public val intValue: Int) {
  DEFAULT(0),
  TEXT(1);

  public fun intValue(): Int = intValue

  public companion object {
    @JvmStatic
    public fun fromInt(value: Int): YogaNodeType =
        when (value) {
          0 -> DEFAULT
          1 -> TEXT
          else -> throw IllegalArgumentException("Unknown enum value: $value")
        }
  }
}
