load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "jsc",
    srcs = glob(["**/*.java"]),
    provided_deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/fabric:fabric"),
        react_native_target("java/com/facebook/react/fabric/jsc/jni:jni"),
    ],
    exported_deps = [
        react_native_dep("java/com/facebook/jni:jni"),
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
    ],
)
