include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'drawer',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_target('java/com/facebook/csslayout:csslayout'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_target('java/com/facebook/react/views/scroll:scroll'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    '//third-party/java/android/support/v4:lib-support-v4',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':drawer',
)
