include_defs("//ReactAndroid/DEFS")

android_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("res:uimanager"),
    ],
)
