/**
 * @generated by scripts/bump-oss-version.js
 *
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#define RCT_REACT_NATIVE_VERSION @{ \
  @"major": @(0), \
  @"minor": @(50), \
  @"patch": @(1), \
  @"prerelease": [NSNull null], \
}
