#!/bin/bash

set -e

DIR=$(cd -P "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)
cd "${DIR}/msggen"

yarn install
yarn build

MSGTYPES_PATH="${DIR}/message_types.txt"
HEADER_PATH="${DIR}/../chrome/MessageTypes.h"
CPP_PATH="${DIR}/../chrome/MessageTypes.cpp"

node bin/index.js \
  --ignore-experimental \
  --include-experimental=Runtime.getHeapUsage \
  --roots "$MSGTYPES_PATH" \
  "$HEADER_PATH" "$CPP_PATH"

clang-format -i --style=file "$HEADER_PATH"
clang-format -i --style=file "$CPP_PATH"

FBSOURCE=$(hg root)
"${FBSOURCE}/tools/signedsource" sign "$HEADER_PATH"
"${FBSOURCE}/tools/signedsource" sign "$CPP_PATH"
