/**
 * @generated
 * @providesModule Metadata
 */
module.exports = {
  "files": [
    {
      "id": "activityindicator",
      "title": "ActivityIndicator",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/activityindicator.html",
      "platform": "cross",
      "next": "button",
      "previous": null,
      "sidebar": true,
      "path": "Libraries/Components/ActivityIndicator/ActivityIndicator.js",
      "filename": null
    },
    {
      "id": "button",
      "title": "Button",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/button.html",
      "platform": "cross",
      "next": "datepickerios",
      "previous": "activityindicator",
      "sidebar": true,
      "path": "Libraries/Components/Button.js",
      "filename": null
    },
    {
      "id": "datepickerios",
      "title": "DatePickerIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/datepickerios.html",
      "platform": "ios",
      "next": "drawerlayoutandroid",
      "previous": "button",
      "sidebar": true,
      "path": "Libraries/Components/DatePicker/DatePickerIOS.ios.js",
      "filename": null
    },
    {
      "id": "drawerlayoutandroid",
      "title": "DrawerLayoutAndroid",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/drawerlayoutandroid.html",
      "platform": "android",
      "next": "flatlist",
      "previous": "datepickerios",
      "sidebar": true,
      "path": "Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js",
      "filename": null
    },
    {
      "id": "flatlist",
      "title": "FlatList",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/flatlist.html",
      "platform": "cross",
      "next": "image",
      "previous": "drawerlayoutandroid",
      "sidebar": true,
      "path": "Libraries/Lists/FlatList.js",
      "filename": null
    },
    {
      "id": "image",
      "title": "Image",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/image.html",
      "platform": "cross",
      "next": "keyboardavoidingview",
      "previous": "flatlist",
      "sidebar": true,
      "path": "Libraries/Image/Image.ios.js",
      "filename": null
    },
    {
      "id": "keyboardavoidingview",
      "title": "KeyboardAvoidingView",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/keyboardavoidingview.html",
      "platform": "cross",
      "next": "listview",
      "previous": "image",
      "sidebar": true,
      "path": "Libraries/Components/Keyboard/KeyboardAvoidingView.js",
      "filename": null
    },
    {
      "id": "listview",
      "title": "ListView",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/listview.html",
      "platform": "cross",
      "next": "maskedviewios",
      "previous": "keyboardavoidingview",
      "sidebar": true,
      "path": "Libraries/Lists/ListView/ListView.js",
      "filename": null
    },
    {
      "id": "maskedviewios",
      "title": "MaskedViewIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/maskedviewios.html",
      "platform": "ios",
      "next": "modal",
      "previous": "listview",
      "sidebar": true,
      "path": "Libraries/Components/MaskedView/MaskedViewIOS.ios.js",
      "filename": null
    },
    {
      "id": "modal",
      "title": "Modal",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/modal.html",
      "platform": "cross",
      "next": "navigatorios",
      "previous": "maskedviewios",
      "sidebar": true,
      "path": "Libraries/Modal/Modal.js",
      "filename": null
    },
    {
      "id": "navigatorios",
      "title": "NavigatorIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/navigatorios.html",
      "platform": "ios",
      "next": "picker",
      "previous": "modal",
      "sidebar": true,
      "path": "Libraries/Components/Navigation/NavigatorIOS.ios.js",
      "filename": null
    },
    {
      "id": "picker",
      "title": "Picker",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/picker.html",
      "platform": "cross",
      "next": "pickerios",
      "previous": "navigatorios",
      "sidebar": true,
      "path": "Libraries/Components/Picker/Picker.js",
      "filename": null
    },
    {
      "id": "pickerios",
      "title": "PickerIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/pickerios.html",
      "platform": "ios",
      "next": "progressbarandroid",
      "previous": "picker",
      "sidebar": true,
      "path": "Libraries/Components/Picker/PickerIOS.ios.js",
      "filename": null
    },
    {
      "id": "progressbarandroid",
      "title": "ProgressBarAndroid",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/progressbarandroid.html",
      "platform": "android",
      "next": "progressviewios",
      "previous": "pickerios",
      "sidebar": true,
      "path": "Libraries/Components/ProgressBarAndroid/ProgressBarAndroid.android.js",
      "filename": null
    },
    {
      "id": "progressviewios",
      "title": "ProgressViewIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/progressviewios.html",
      "platform": "ios",
      "next": "refreshcontrol",
      "previous": "progressbarandroid",
      "sidebar": true,
      "path": "Libraries/Components/ProgressViewIOS/ProgressViewIOS.ios.js",
      "filename": null
    },
    {
      "id": "refreshcontrol",
      "title": "RefreshControl",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/refreshcontrol.html",
      "platform": "cross",
      "next": "scrollview",
      "previous": "progressviewios",
      "sidebar": true,
      "path": "Libraries/Components/RefreshControl/RefreshControl.js",
      "filename": null
    },
    {
      "id": "scrollview",
      "title": "ScrollView",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/scrollview.html",
      "platform": "cross",
      "next": "sectionlist",
      "previous": "refreshcontrol",
      "sidebar": true,
      "path": "Libraries/Components/ScrollView/ScrollView.js",
      "filename": null
    },
    {
      "id": "sectionlist",
      "title": "SectionList",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/sectionlist.html",
      "platform": "cross",
      "next": "segmentedcontrolios",
      "previous": "scrollview",
      "sidebar": true,
      "path": "Libraries/Lists/SectionList.js",
      "filename": null
    },
    {
      "id": "segmentedcontrolios",
      "title": "SegmentedControlIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/segmentedcontrolios.html",
      "platform": "ios",
      "next": "slider",
      "previous": "sectionlist",
      "sidebar": true,
      "path": "Libraries/Components/SegmentedControlIOS/SegmentedControlIOS.ios.js",
      "filename": null
    },
    {
      "id": "slider",
      "title": "Slider",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/slider.html",
      "platform": "cross",
      "next": "snapshotviewios",
      "previous": "segmentedcontrolios",
      "sidebar": true,
      "path": "Libraries/Components/Slider/Slider.js",
      "filename": null
    },
    {
      "id": "snapshotviewios",
      "title": "SnapshotViewIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/snapshotviewios.html",
      "platform": "ios",
      "next": "statusbar",
      "previous": "slider",
      "sidebar": true,
      "path": "Libraries/RCTTest/SnapshotViewIOS.ios.js",
      "filename": null
    },
    {
      "id": "statusbar",
      "title": "StatusBar",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/statusbar.html",
      "platform": "cross",
      "next": "switch",
      "previous": "snapshotviewios",
      "sidebar": true,
      "path": "Libraries/Components/StatusBar/StatusBar.js",
      "filename": null
    },
    {
      "id": "switch",
      "title": "Switch",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/switch.html",
      "platform": "cross",
      "next": "tabbarios",
      "previous": "statusbar",
      "sidebar": true,
      "path": "Libraries/Components/Switch/Switch.js",
      "filename": null
    },
    {
      "id": "tabbarios",
      "title": "TabBarIOS",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/tabbarios.html",
      "platform": "ios",
      "next": "tabbarios-item",
      "previous": "switch",
      "sidebar": true,
      "path": "Libraries/Components/TabBarIOS/TabBarIOS.ios.js",
      "filename": null
    },
    {
      "id": "tabbarios-item",
      "title": "TabBarIOS.Item",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/tabbarios-item.html",
      "platform": "ios",
      "next": "text",
      "previous": "tabbarios",
      "sidebar": true,
      "path": "Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js",
      "filename": null
    },
    {
      "id": "text",
      "title": "Text",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/text.html",
      "platform": "cross",
      "next": "textinput",
      "previous": "tabbarios-item",
      "sidebar": true,
      "path": "Libraries/Text/Text.js",
      "filename": null
    },
    {
      "id": "textinput",
      "title": "TextInput",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/textinput.html",
      "platform": "cross",
      "next": "toolbarandroid",
      "previous": "text",
      "sidebar": true,
      "path": "Libraries/Components/TextInput/TextInput.js",
      "filename": null
    },
    {
      "id": "toolbarandroid",
      "title": "ToolbarAndroid",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/toolbarandroid.html",
      "platform": "android",
      "next": "touchablehighlight",
      "previous": "textinput",
      "sidebar": true,
      "path": "Libraries/Components/ToolbarAndroid/ToolbarAndroid.android.js",
      "filename": null
    },
    {
      "id": "touchablehighlight",
      "title": "TouchableHighlight",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/touchablehighlight.html",
      "platform": "cross",
      "next": "touchablenativefeedback",
      "previous": "toolbarandroid",
      "sidebar": true,
      "path": "Libraries/Components/Touchable/TouchableHighlight.js",
      "filename": null
    },
    {
      "id": "touchablenativefeedback",
      "title": "TouchableNativeFeedback",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/touchablenativefeedback.html",
      "platform": "cross",
      "next": "touchableopacity",
      "previous": "touchablehighlight",
      "sidebar": true,
      "path": "Libraries/Components/Touchable/TouchableNativeFeedback.android.js",
      "filename": null
    },
    {
      "id": "touchableopacity",
      "title": "TouchableOpacity",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/touchableopacity.html",
      "platform": "cross",
      "next": "touchablewithoutfeedback",
      "previous": "touchablenativefeedback",
      "sidebar": true,
      "path": "Libraries/Components/Touchable/TouchableOpacity.js",
      "filename": null
    },
    {
      "id": "touchablewithoutfeedback",
      "title": "TouchableWithoutFeedback",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/touchablewithoutfeedback.html",
      "platform": "cross",
      "next": "view",
      "previous": "touchableopacity",
      "sidebar": true,
      "path": "Libraries/Components/Touchable/TouchableWithoutFeedback.js",
      "filename": null
    },
    {
      "id": "view",
      "title": "View",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/view.html",
      "platform": "cross",
      "next": "viewpagerandroid",
      "previous": "touchablewithoutfeedback",
      "sidebar": true,
      "path": "Libraries/Components/View/View.js",
      "filename": null
    },
    {
      "id": "viewpagerandroid",
      "title": "ViewPagerAndroid",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/viewpagerandroid.html",
      "platform": "android",
      "next": "virtualizedlist",
      "previous": "view",
      "sidebar": true,
      "path": "Libraries/Components/ViewPager/ViewPagerAndroid.android.js",
      "filename": null
    },
    {
      "id": "virtualizedlist",
      "title": "VirtualizedList",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/virtualizedlist.html",
      "platform": "cross",
      "next": "webview",
      "previous": "viewpagerandroid",
      "sidebar": true,
      "path": "Libraries/Lists/VirtualizedList.js",
      "filename": null
    },
    {
      "id": "webview",
      "title": "WebView",
      "layout": "autodocs",
      "category": "Components",
      "permalink": "docs/webview.html",
      "platform": "cross",
      "next": "accessibilityinfo",
      "previous": "virtualizedlist",
      "sidebar": true,
      "path": "Libraries/Components/WebView/WebView.ios.js",
      "filename": null
    },
    {
      "id": "accessibilityinfo",
      "title": "AccessibilityInfo",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/accessibilityinfo.html",
      "platform": "cross",
      "next": "actionsheetios",
      "previous": "webview",
      "sidebar": true,
      "path": "Libraries/Components/AccessibilityInfo/AccessibilityInfo.ios.js",
      "filename": null
    },
    {
      "id": "actionsheetios",
      "title": "ActionSheetIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/actionsheetios.html",
      "platform": "ios",
      "next": "alert",
      "previous": "accessibilityinfo",
      "sidebar": true,
      "path": "Libraries/ActionSheetIOS/ActionSheetIOS.js",
      "filename": null
    },
    {
      "id": "alert",
      "title": "Alert",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/alert.html",
      "platform": "cross",
      "next": "alertios",
      "previous": "actionsheetios",
      "sidebar": true,
      "path": "Libraries/Alert/Alert.js",
      "filename": null
    },
    {
      "id": "alertios",
      "title": "AlertIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/alertios.html",
      "platform": "ios",
      "next": "animated",
      "previous": "alert",
      "sidebar": true,
      "path": "Libraries/Alert/AlertIOS.js",
      "filename": null
    },
    {
      "id": "animated",
      "title": "Animated",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/animated.html",
      "platform": "cross",
      "next": "appregistry",
      "previous": "alertios",
      "sidebar": true,
      "path": "Libraries/Animated/src/AnimatedImplementation.js",
      "filename": null
    },
    {
      "id": "appregistry",
      "title": "AppRegistry",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/appregistry.html",
      "platform": "cross",
      "next": "appstate",
      "previous": "animated",
      "sidebar": true,
      "path": "Libraries/ReactNative/AppRegistry.js",
      "filename": null
    },
    {
      "id": "appstate",
      "title": "AppState",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/appstate.html",
      "platform": "cross",
      "next": "asyncstorage",
      "previous": "appregistry",
      "sidebar": true,
      "path": "Libraries/AppState/AppState.js",
      "filename": null
    },
    {
      "id": "asyncstorage",
      "title": "AsyncStorage",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/asyncstorage.html",
      "platform": "cross",
      "next": "backandroid",
      "previous": "appstate",
      "sidebar": true,
      "path": "Libraries/Storage/AsyncStorage.js",
      "filename": null
    },
    {
      "id": "backandroid",
      "title": "BackAndroid",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/backandroid.html",
      "platform": "android",
      "next": "backhandler",
      "previous": "asyncstorage",
      "sidebar": true,
      "path": "Libraries/Utilities/BackAndroid.js",
      "filename": null
    },
    {
      "id": "backhandler",
      "title": "BackHandler",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/backhandler.html",
      "platform": "cross",
      "next": "backhandler",
      "previous": "backandroid",
      "sidebar": true,
      "path": "Libraries/Utilities/BackHandler.ios.js",
      "filename": null
    },
    {
      "id": "backhandler",
      "title": "BackHandler",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/backhandler.html",
      "platform": "cross",
      "next": "cameraroll",
      "previous": "backhandler",
      "sidebar": true,
      "path": "Libraries/Utilities/BackHandler.android.js",
      "filename": null
    },
    {
      "id": "cameraroll",
      "title": "CameraRoll",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/cameraroll.html",
      "platform": "cross",
      "next": "clipboard",
      "previous": "backhandler",
      "sidebar": true,
      "path": "Libraries/CameraRoll/CameraRoll.js",
      "filename": null
    },
    {
      "id": "clipboard",
      "title": "Clipboard",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/clipboard.html",
      "platform": "cross",
      "next": "datepickerandroid",
      "previous": "cameraroll",
      "sidebar": true,
      "path": "Libraries/Components/Clipboard/Clipboard.js",
      "filename": null
    },
    {
      "id": "datepickerandroid",
      "title": "DatePickerAndroid",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/datepickerandroid.html",
      "platform": "android",
      "next": "dimensions",
      "previous": "clipboard",
      "sidebar": true,
      "path": "Libraries/Components/DatePickerAndroid/DatePickerAndroid.android.js",
      "filename": null
    },
    {
      "id": "dimensions",
      "title": "Dimensions",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/dimensions.html",
      "platform": "cross",
      "next": "easing",
      "previous": "datepickerandroid",
      "sidebar": true,
      "path": "Libraries/Utilities/Dimensions.js",
      "filename": null
    },
    {
      "id": "easing",
      "title": "Easing",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/easing.html",
      "platform": "cross",
      "next": "geolocation",
      "previous": "dimensions",
      "sidebar": true,
      "path": "Libraries/Animated/src/Easing.js",
      "filename": null
    },
    {
      "id": "geolocation",
      "title": "Geolocation",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/geolocation.html",
      "platform": "cross",
      "next": "imageeditor",
      "previous": "easing",
      "sidebar": true,
      "path": "Libraries/Geolocation/Geolocation.js",
      "filename": null
    },
    {
      "id": "imageeditor",
      "title": "ImageEditor",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/imageeditor.html",
      "platform": "cross",
      "next": "imagepickerios",
      "previous": "geolocation",
      "sidebar": true,
      "path": "Libraries/Image/ImageEditor.js",
      "filename": null
    },
    {
      "id": "imagepickerios",
      "title": "ImagePickerIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/imagepickerios.html",
      "platform": "ios",
      "next": "imagestore",
      "previous": "imageeditor",
      "sidebar": true,
      "path": "Libraries/CameraRoll/ImagePickerIOS.js",
      "filename": null
    },
    {
      "id": "imagestore",
      "title": "ImageStore",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/imagestore.html",
      "platform": "cross",
      "next": "interactionmanager",
      "previous": "imagepickerios",
      "sidebar": true,
      "path": "Libraries/Image/ImageStore.js",
      "filename": null
    },
    {
      "id": "interactionmanager",
      "title": "InteractionManager",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/interactionmanager.html",
      "platform": "cross",
      "next": "keyboard",
      "previous": "imagestore",
      "sidebar": true,
      "path": "Libraries/Interaction/InteractionManager.js",
      "filename": null
    },
    {
      "id": "keyboard",
      "title": "Keyboard",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/keyboard.html",
      "platform": "cross",
      "next": "layoutanimation",
      "previous": "interactionmanager",
      "sidebar": true,
      "path": "Libraries/Components/Keyboard/Keyboard.js",
      "filename": null
    },
    {
      "id": "layoutanimation",
      "title": "LayoutAnimation",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/layoutanimation.html",
      "platform": "cross",
      "next": "linking",
      "previous": "keyboard",
      "sidebar": true,
      "path": "Libraries/LayoutAnimation/LayoutAnimation.js",
      "filename": null
    },
    {
      "id": "linking",
      "title": "Linking",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/linking.html",
      "platform": "cross",
      "next": "netinfo",
      "previous": "layoutanimation",
      "sidebar": true,
      "path": "Libraries/Linking/Linking.js",
      "filename": null
    },
    {
      "id": "netinfo",
      "title": "NetInfo",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/netinfo.html",
      "platform": "cross",
      "next": "panresponder",
      "previous": "linking",
      "sidebar": true,
      "path": "Libraries/Network/NetInfo.js",
      "filename": null
    },
    {
      "id": "panresponder",
      "title": "PanResponder",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/panresponder.html",
      "platform": "cross",
      "next": "permissionsandroid",
      "previous": "netinfo",
      "sidebar": true,
      "path": "Libraries/Interaction/PanResponder.js",
      "filename": null
    },
    {
      "id": "permissionsandroid",
      "title": "PermissionsAndroid",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/permissionsandroid.html",
      "platform": "android",
      "next": "pixelratio",
      "previous": "panresponder",
      "sidebar": true,
      "path": "Libraries/PermissionsAndroid/PermissionsAndroid.js",
      "filename": null
    },
    {
      "id": "pixelratio",
      "title": "PixelRatio",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/pixelratio.html",
      "platform": "cross",
      "next": "pushnotificationios",
      "previous": "permissionsandroid",
      "sidebar": true,
      "path": "Libraries/Utilities/PixelRatio.js",
      "filename": null
    },
    {
      "id": "pushnotificationios",
      "title": "PushNotificationIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/pushnotificationios.html",
      "platform": "ios",
      "next": "settings",
      "previous": "pixelratio",
      "sidebar": true,
      "path": "Libraries/PushNotificationIOS/PushNotificationIOS.js",
      "filename": null
    },
    {
      "id": "settings",
      "title": "Settings",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/settings.html",
      "platform": "cross",
      "next": "share",
      "previous": "pushnotificationios",
      "sidebar": true,
      "path": "Libraries/Settings/Settings.ios.js",
      "filename": null
    },
    {
      "id": "share",
      "title": "Share",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/share.html",
      "platform": "cross",
      "next": "statusbarios",
      "previous": "settings",
      "sidebar": true,
      "path": "Libraries/Share/Share.js",
      "filename": null
    },
    {
      "id": "statusbarios",
      "title": "StatusBarIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/statusbarios.html",
      "platform": "ios",
      "next": "stylesheet",
      "previous": "share",
      "sidebar": true,
      "path": "Libraries/Components/StatusBar/StatusBarIOS.ios.js",
      "filename": null
    },
    {
      "id": "stylesheet",
      "title": "StyleSheet",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/stylesheet.html",
      "platform": "cross",
      "next": "systrace",
      "previous": "statusbarios",
      "sidebar": true,
      "path": "Libraries/StyleSheet/StyleSheet.js",
      "filename": null
    },
    {
      "id": "systrace",
      "title": "Systrace",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/systrace.html",
      "platform": "cross",
      "next": "timepickerandroid",
      "previous": "stylesheet",
      "sidebar": true,
      "path": "Libraries/Performance/Systrace.js",
      "filename": null
    },
    {
      "id": "timepickerandroid",
      "title": "TimePickerAndroid",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/timepickerandroid.html",
      "platform": "android",
      "next": "toastandroid",
      "previous": "systrace",
      "sidebar": true,
      "path": "Libraries/Components/TimePickerAndroid/TimePickerAndroid.android.js",
      "filename": null
    },
    {
      "id": "toastandroid",
      "title": "ToastAndroid",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/toastandroid.html",
      "platform": "android",
      "next": "vibration",
      "previous": "timepickerandroid",
      "sidebar": true,
      "path": "Libraries/Components/ToastAndroid/ToastAndroid.android.js",
      "filename": null
    },
    {
      "id": "vibration",
      "title": "Vibration",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/vibration.html",
      "platform": "cross",
      "next": "vibrationios",
      "previous": "toastandroid",
      "sidebar": true,
      "path": "Libraries/Vibration/Vibration.js",
      "filename": null
    },
    {
      "id": "vibrationios",
      "title": "VibrationIOS",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/vibrationios.html",
      "platform": "ios",
      "next": "layout-props",
      "previous": "vibration",
      "sidebar": true,
      "path": "Libraries/Vibration/VibrationIOS.ios.js",
      "filename": null
    },
    {
      "id": "layout-props",
      "title": "Layout Props",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/layout-props.html",
      "platform": "cross",
      "next": "shadow-props",
      "previous": "vibrationios",
      "sidebar": true,
      "path": "Libraries/StyleSheet/LayoutPropTypes.js",
      "filename": null
    },
    {
      "id": "shadow-props",
      "title": "Shadow Props",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/shadow-props.html",
      "platform": "ios",
      "next": "viewproptypes",
      "previous": "layout-props",
      "sidebar": true,
      "path": "Libraries/Components/View/ShadowPropTypesIOS.js",
      "filename": null
    },
    {
      "id": "viewproptypes",
      "title": "ViewPropTypes",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/viewproptypes.html",
      "platform": "cross",
      "next": "viewstyleproptypes",
      "previous": "shadow-props",
      "sidebar": true,
      "path": "Libraries/Components/View/ViewPropTypes.js",
      "filename": null
    },
    {
      "id": "viewstyleproptypes",
      "title": "ViewStylePropTypes",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/viewstyleproptypes.html",
      "platform": "cross",
      "next": "textstyleproptypes",
      "previous": "viewproptypes",
      "sidebar": true,
      "path": "Libraries/Components/View/ViewStylePropTypes.js",
      "filename": null
    },
    {
      "id": "textstyleproptypes",
      "title": "TextStylePropTypes",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/textstyleproptypes.html",
      "platform": "cross",
      "next": "imagestyleproptypes",
      "previous": "viewstyleproptypes",
      "sidebar": true,
      "path": "Libraries/Text/TextStylePropTypes.js",
      "filename": null
    },
    {
      "id": "imagestyleproptypes",
      "title": "ImageStylePropTypes",
      "layout": "autodocs",
      "category": "APIs",
      "permalink": "docs/imagestyleproptypes.html",
      "platform": "cross",
      "next": null,
      "previous": "textstyleproptypes",
      "sidebar": true,
      "path": "Libraries/Image/ImageStylePropTypes.js",
      "filename": null
    }
  ],
  "config": {}
};