load("//tools/build_defs/oss:rn_defs.bzl", "rn_android_library", "react_native_dep", "react_native_target", "rn_xplat_cxx_library")

rn_android_library(
    name = "reactexecutor",
    srcs = [
        "HermesExecutor.java",
        "HermesExecutorFactory.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/hermes/instrumentation:instrumentation"),
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        ":jni",
        ":runtimeconfig",
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)

rn_android_library(
    name = "reactexecutor-hermes-snapshot",
    srcs = [
        "HermesSnapshotExecutor.java",
        "HermesSnapshotExecutorFactory.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/hermes/instrumentation:instrumentation"),
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        ":jni-hermes-snapshot",
        ":runtimeconfig",
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)

rn_android_library(
    name = "runtimeconfig",
    srcs = [
        "RuntimeConfig.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/hermes/instrumentation:instrumentation"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)

rn_xplat_cxx_library(
    name = "jni-interface",
    srcs = [],
    header_namespace = "hermes/reactexecutor",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//xplat/hermes/public:public",
    ],
)

rn_xplat_cxx_library(
    name = "jni-interface-snapshot",
    srcs = [],
    header_namespace = "hermes/reactexecutor",
    exported_headers = glob(["*.h"]),
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//xplat/hermes-snapshot/public:public",
    ],
)

rn_xplat_cxx_library(
    name = "jni",
    srcs = ["OnLoad.cpp"],
    headers = [],
    header_namespace = "",
    allow_jni_merging = True,
    compiler_flags = ["-fexceptions"],
    soname = "libhermes-executor.$(ext)",
    visibility = [
        react_native_dep("java/com/facebook/hermes/reactexecutor:reactexecutor"),
    ],
    deps = [
        react_native_dep("java/com/facebook/hermes/crashmanager:crashmanager"),
        react_native_dep("java/com/facebook/hermes/instrumentation:jni-interface"),
        react_native_dep("java/com/facebook/quicklog/jni:qpljsibindings"),
        react_native_dep("native/fb:fb"),
        "fbsource//xplat/MobileCoreHealth/fbsofterror:fbsofterror",
        "fbsource//xplat/folly:memory",
        "fbsource//xplat/hermes/API:HermesAPI",
        ":jni-interface",
        react_native_target("jni/react/jni:jni"),
        "fbsource//xplat/ReactNative/react/jsi:HermesExecutorFactory",
    ],
)

rn_xplat_cxx_library(
    name = "jni-hermes-snapshot",
    srcs = ["OnLoadSnapshot.cpp"],
    headers = [],
    header_namespace = "",
    allow_jni_merging = True,
    compiler_flags = ["-fexceptions"],
    soname = "libhermes-executor-snapshot.$(ext)",
    visibility = [
        react_native_dep("java/com/facebook/hermes/reactexecutor:reactexecutor"),
    ],
    deps = [
        react_native_dep("java/com/facebook/hermes/instrumentation:jni-interface"),
        react_native_dep("java/com/facebook/quicklog/jni:qpljsibindings"),
        react_native_dep("native/fb:fb"),
        "fbsource//xplat/MobileCoreHealth/fbsofterror:fbsofterror",
        "fbsource//xplat/folly:memory",
        "fbsource//xplat/hermes-snapshot/API:HermesAPI",
        ":jni-interface-snapshot",
        react_native_target("jni/react/jni:jni"),
        "fbsource//xplat/ReactNative/react/jsi:HermesSnapshotExecutorFactory",
    ],
)
