load("//ReactNative:DEFS.bzl", "cxx_library")

# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

cxx_library(
    name = "jni-hack",
    header_namespace = "",
    exported_headers = [
        "jni.h",
        "real/jni.h",
    ],
    force_static = True,
    visibility = ["PUBLIC"],
)
