include_defs("//ReactAndroid/DEFS")

android_library(
    name = "tags",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/debug/debugoverlay:debugoverlay"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)
