load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "rn_android_library")

rn_android_library(
    name = "tags",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/android/androidx:annotation"),
    ],
    exported_deps = [
        react_native_dep("java/com/facebook/debug/debugoverlay/model:model"),
    ],
)
