include_defs('//ReactAndroid/DEFS')

DEPS = [
  react_native_target('java/com/facebook/react/bridge:bridge'),
  react_native_target('java/com/facebook/react/common:common'),
  react_native_target('java/com/facebook/react/uimanager:uimanager'),
  react_native_dep('libraries/fbcore/src/main/java/com/facebook/common/logging:logging'),
  react_native_dep('third-party/java/infer-annotations:infer-annotations'),
  react_native_dep('third-party/java/jsr-305:jsr-305'),
]

android_library(
  name = 'jstasks',
  srcs = glob(['*.java']),
  deps = DEPS,
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':jstasks',
)
