load("//ReactNative:DEFS.bzl", "react_native_target", "rn_android_library")

rn_android_library(
    name = "util",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)
