load("@fbsource//xplat/pfh/ReactNative/CommonInfrastructurePlaceholde:DEFS.bzl", "ReactNative_CommonInfrastructurePlaceholde")
load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "rn_android_library")

rn_android_library(
    name = "config",
    srcs = glob(["**/*.java"]),
    autoglob = False,
    feature = ReactNative_CommonInfrastructurePlaceholde,
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
    ],
)
