include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'uimanager',
  srcs = glob(['**/*.java']),
  deps = [
    '//libraries/fbcore/src/main/java/com/facebook/common/logging:logging',
    react_native_target('java/com/facebook/react/animation:animation'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/csslayout:csslayout'),
    react_native_target('java/com/facebook/react/touch:touch'),
    react_native_dep('java/com/facebook/systrace:systrace'),
    react_native_dep('third-party/java/infer-annotations:infer-annotations'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    react_native_dep('third-party/java/android/support/v4:lib-support-v4'),
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':uimanager',
)
