load("//ReactNative:DEFS.bzl", "rn_android_library", "YOGA_TARGET", "react_native_dep", "react_native_target")

rn_android_library(
    name = "uimanager",
    srcs = glob(
        [
            "*.java",
            "debug/*.java",
            "events/*.java",
            "layoutanimation/*.java",
        ],
        excludes = ["DisplayMetricsHolder.java"],
    ),
    exported_deps = [
        ":DisplayMetrics",
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
    provided_deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/android/support-annotations:android-support-annotations"),
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        YOGA_TARGET,
        ":DisplayMetrics",
        react_native_dep("java/com/facebook/systrace:systrace"),
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_target("java/com/facebook/debug/tags:tags"),
        react_native_target("java/com/facebook/debug/holder:holder"),
        react_native_target("java/com/facebook/react/animation:animation"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
        react_native_target("java/com/facebook/react/modules/core:core"),
        react_native_target("java/com/facebook/react/modules/i18nmanager:i18nmanager"),
        react_native_target("java/com/facebook/react/touch:touch"),
        react_native_target("java/com/facebook/react/uimanager/annotations:annotations"),
        react_native_target("java/com/facebook/react/uimanager/util:util"),
        react_native_target("res:uimanager"),
    ],
)

rn_android_library(
    name = "DisplayMetrics",
    srcs = glob([
        "DisplayMetricsHolder.java",
    ]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)
