# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:rn_codegen_defs.bzl",
    "rn_codegen",
)

rn_codegen(
    name = "FBReactNativeSpec",
    android_package_name = "com.facebook.fbreact.specs",
    codegen_modules = True,
    library_labels = ["supermodule:xplat/default/public.react_native.infra"],
    native_module_spec_name = "FBReactNativeSpec",
)

# TODO: Merge this into FBReactNativeSpec
rn_codegen(
    name = "FBReactNativeComponentSpec",
    codegen_components = True,
    library_labels = ["supermodule:xplat/default/public.react_native.infra"],
)
