load("//ReactNative:DEFS.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "annotations",
    srcs = glob(["**/*.java"]),
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)
