include_defs('//ReactAndroid/DEFS')

rn_robolectric_test(
  name = 'animated',
  # Please change the contact to the oncall of your team
  contacts = ['oncall+fbandroid_sheriff@xmail.facebook.com'],
  srcs = glob(['**/*.java']),
  deps = [
    react_native_dep('libraries/fbcore/src/test/java/com/facebook/powermock:powermock'),
    react_native_dep('third-party/java/fest:fest'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    react_native_dep('third-party/java/junit:junit'),
    react_native_dep('third-party/java/mockito:mockito'),
    react_native_dep('third-party/java/robolectric3/robolectric:robolectric'),
    react_native_target('java/com/facebook/react:react'),
    react_native_target('java/com/facebook/react/animated:animated'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_tests_target('java/com/facebook/react/bridge:testhelpers'),
  ],
  visibility = [
    'PUBLIC'
  ],
)

