cxx_library(
    name = "microprofiler",
    srcs = [
        "MicroProfiler.cpp",
    ],
    compiler_flags = [
        "-Wall",
        "-Werror",
        "-std=c++11",
        "-fexceptions",
    ],
    exported_headers = [
        "MicroProfiler.h",
    ],
    force_static = True,
    header_namespace = "microprofiler",
    visibility = [
        "PUBLIC",
    ],
    xcode_public_headers_symlinks = True,
    deps = [
        "//xplat/third-party/glog:glog",
    ],
)
