include_defs("//ReactAndroid/DEFS")

android_library(
    name = "bridge",
    srcs = glob(["**/*.java"]),
    exported_deps = [
        react_native_dep("java/com/facebook/jni:jni"),
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
        react_native_dep("third-party/java/jsr-330:jsr-330"),
    ],
    proguard_config = "reactnative.pro",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/systrace:systrace"),
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/model:model"),
    ] + ([react_native_target("jni/react/jni:jni")] if not IS_OSS_BUILD else []),
)
