include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'switchview',
  srcs = glob(['*.java']),
  deps = [
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/csslayout:csslayout'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    '//third-party/android-support-for-standalone-apps/v7/appcompat:appcompat-23.1',
    '//third-party/android-support-for-standalone-apps/v7/appcompat:res-for-react-native',
    '//third-party/java/jsr-305:jsr-305',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':switchview',
)
