/**
 * @generated by scripts/bump-oss-version.js
 *
<<<<<<< HEAD
 * Copyright (c) 2015-present, Facebook, Inc.
=======
 * Copyright (c) Facebook, Inc. and its affiliates.
>>>>>>> v0.58.6
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow
 */

exports.version = {
  major: 0,
  minor: 58,
  patch: 6,
  prerelease: null,
};
