load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "fresco",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/systrace:systrace"),
        react_native_dep("third-party/android/fbcore:fbcore"),
        react_native_dep("third-party/android/fbcore:fbcore"),
        react_native_dep("third-party/android/fresco:fresco-drawee"),
        react_native_dep("third-party/android/fresco:fresco-react-native"),
        react_native_dep("third-party/android/fresco:imagepipeline"),
        react_native_dep("third-party/android/fresco:imagepipeline-okhttp3"),
        react_native_dep("third-party/android/soloader:soloader"),
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okhttp:okhttp3-urlconnection"),
        react_native_dep("third-party/java/okio:okio"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
        react_native_target("java/com/facebook/react/modules/common:common"),
        react_native_target("java/com/facebook/react/modules/network:network"),
    ],
)
