load("//ReactNative:DEFS.bzl", "rn_android_library", "react_native_dep", "react_native_target")

android_library(
    name = "fabric",
    srcs = glob(["*.java"]),
    provided_deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("libraries/fresco/fresco-react-native:fbcore"),
        react_native_dep("libraries/fresco/fresco-react-native:fresco-drawee"),
        react_native_dep("libraries/fresco/fresco-react-native:fresco-react-native"),
        react_native_dep("libraries/fresco/fresco-react-native:imagepipeline"),
        react_native_dep("libraries/textlayoutbuilder:textlayoutbuilder"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react:reactAndroid"),
        react_native_target("java/com/facebook/react/bridge:bridgeAndroid"),
        react_native_target("java/com/facebook/react/common:commonAndroid"),
        react_native_target("java/com/facebook/react/devsupport:devsupportAndroid"),
        react_native_target("java/com/facebook/react/modules/core:coreAndroid"),
        react_native_target("java/com/facebook/react/shell:shellAndroid"),
        react_native_target("java/com/facebook/react/uimanager:uimanagerAndroid"),
        react_native_target("java/com/facebook/react/uimanager/annotations:annotationsAndroid"),
        react_native_target("java/com/facebook/react/module/annotations:annotationsAndroid"),
    ],
)
