load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library", "react_native_xplat_target_apple", "subdir_glob")

fb_apple_library(
    name = "FBReactNativeSpecApple",
    srcs = glob(["FBReactNativeSpec/**/*.mm"]),
    exported_headers = subdir_glob(
        [
            ("FBReactNativeSpec", "*.h"),
        ],
        prefix = "FBReactNativeSpec",
    ),
    contacts = ["oncall+react_native@xmail.facebook.com"],
    extension_api_only = True,
    frameworks = [
        "Foundation",
        "UIKit",
    ],
    labels = ["supermodule:ios/default/public.react_native.infra"],
    reexport_all_header_dependencies = True,
    deps = [
        "//xplat/js/react-native-github:RCTTypeSafety",
        "//xplat/js/react-native-github/Libraries/RCTRequired:RCTRequired",
        react_native_xplat_target_apple("turbomodule/core:core"),
    ],
)
