name: 🐛 React Native - Bug Report
description: Report a reproducible bug or regression in React Native.
labels: ["Needs: Triage :mag:"]
body:
  - type: markdown
    attributes:
      value: "## Reporting a bug to React Native"
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue for React Native, your contribution will help
        make the framework better for everyone.

        Before you continue:
        * If you're using **Expo** and you're noticing a bug, [report it here](https://github.com/expo/expo/issues).
        * If you're found a problem with our **documentation**, [report it here](https://github.com/facebook/react-native-website/issues/).
        * If you're having an issue with **Metro** (the bundler), [report it here](https://github.com/facebook/metro/issues/).
        * If you're using an external library, report the issue to the **library first**.
        * Please [search for similar issues](https://github.com/facebook/react-native/issues) in our issue tracker.

        Make sure that your issue:
        * Have a **valid reproducer** (either a [Expo Snack](https://snack.expo.dev/) or a [empty project from template](https://github.com/react-native-community/reproducer-react-native).
        * Is tested against the [**latest stable**](https://github.com/facebook/react-native/releases/) of React Native.

        Due to the extreme number of bugs we receive, we will be looking **ONLY** into issues with a reproducer, and on [supported versions](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) of React Native.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: The list of steps that reproduce the issue.
      placeholder: |
        1. Install the application with `yarn android`
        2. Click on the button on the Home
        3. Notice the crash
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: React Native Version
      description: The version of react-native that this issue reproduces on. Bear in mind that only issues on [supported versions](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) will be looked into.
      placeholder: "0.73.0"
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Affected Platforms
      description: Please select which platform you're developing to, and which OS you're using for building.
      multiple: true
      options:
        - Runtime - Android
        - Runtime - iOS
        - Runtime - Web
        - Runtime - Desktop
        - Build - MacOS
        - Build - Windows
        - Build - Linux
        - Other (please specify)
    validations:
      required: true
  - type: textarea
    id: react-native-info
    attributes:
      label: Output of `npx react-native info`
      description: Run `npx react-native info` in your terminal, copy and paste the results here.
      placeholder: |
        Paste the output of `npx react-native info` here. The output looks like:
        ...
        System:
          OS: macOS 14.1.1
          CPU: (10) arm64 Apple M1 Max
          Memory: 417.81 MB / 64.00 GB
          Shell:
            version: "5.9"
            path: /bin/zsh
        Binaries:
          Node: ...
            version: 18.14.0
        ...
      render: text
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace or Logs
      description: Please provide a stacktrace or a log of your crash or failure
      render: text
      placeholder: |
        Paste your stacktraces and logs here. They might look like:

        java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfabricjni.so caused by: com.facebook.react.fabric.StateWrapperImpl result: 0
            at com.facebook.soloader.SoLoader.g(Unknown Source:341)
            at com.facebook.soloader.SoLoader.t(Unknown Source:124)
            at com.facebook.soloader.SoLoader.s(Unknown Source:2)
            at com.facebook.soloader.SoLoader.q(Unknown Source:42)
            at com.facebook.soloader.SoLoader.p(Unknown Source:1)
            ...
    validations:
      required: true
  - type: input
    id: reproducer
    attributes:
      label: Reproducer
      description: A link to a Expo Snack or a public repository that reproduces this bug, using [this template](https://github.com/react-native-community/reproducer-react-native). Reproducers are **mandatory**.
      placeholder: "https://github.com/<myuser>/<myreproducer>"
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Screenshots and Videos
      description: |
        Please provide screenshot or a video of your bug if relevant.
        Issues with videos and screenshots are more likely to **get prioritized**.
