load("@fbsource//tools/build_defs/apple:flag_defs.bzl", "get_debug_preprocessor_flags")
load(
    "//tools/build_defs/oss:rn_defs.bzl",
    "APPLE",
    "get_apple_compiler_flags",
    "get_apple_inspector_flags",
    "react_native_xplat_target",
    "rn_xplat_cxx_library",
    "subdir_glob",
)

APPLE_COMPILER_FLAGS = get_apple_compiler_flags()

rn_xplat_cxx_library(
    name = "legacyviewmanagerinterop",
    srcs = glob(
        [
            "**/*.cpp",
            "**/*.mm",
        ],
    ),
    headers = [],
    header_namespace = "",
    exported_headers = subdir_glob(
        [
            ("", "*.h"),
        ],
        prefix = "react/components/legacyviewmanagerinterop",
    ),
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-std=c++14",
        "-Wall",
    ],
    fbobjc_compiler_flags = APPLE_COMPILER_FLAGS,
    fbobjc_labels = ["supermodule:ios/isolation/infra.react_native"],
    fbobjc_preprocessor_flags = get_debug_preprocessor_flags() + get_apple_inspector_flags(),
    force_static = True,
    platforms = (APPLE),
    preprocessor_flags = [
        "-DLOG_TAG=\"ReactNative\"",
        "-DWITH_FBSYSTRACE=1",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "fbsource//xplat/folly:headers_only",
        "fbsource//xplat/folly:memory",
        react_native_xplat_target("fabric/core:core"),
        react_native_xplat_target("fabric/components/view:view"),
        "fbsource//xplat/js/react-native-github:generated_components-rncore",
    ],
)
