load("//ReactNative:DEFS.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "network",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
        react_native_target("java/com/facebook/react/modules/core:core"),
    ],
)
