load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_target", "react_native_tests_target", "rn_robolectric_test")

rn_robolectric_test(
    name = "devsupport",
    srcs = glob(["**/*.java"]),
    contacts = ["oncall+fbandroid_sheriff@xmail.facebook.com"],
    language = "JAVA",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/assertj:assertj-core"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/junit:junit"),
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okio:okio"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/devsupport:devsupport"),
        react_native_target("java/com/facebook/react/devsupport:interfaces"),
        react_native_tests_target("java/com/facebook/react/bridge:testhelpers"),
    ],
)
