include_defs("//ReactCommon/DEFS")

cxx_library(
    name = "fbgloginit",
    srcs = [
        "glog_init.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-fno-omit-frame-pointer",
    ],
    exported_headers = ["fb/glog_init.h"],
    linker_flags = [
        "-llog",
    ],
    visibility = ["PUBLIC"],
    deps = [
        GLOG_DEP,
    ],
)
