include_defs('//ReactAndroid/DEFS')

android_binary(
  name = 'app',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//keystores:debug',
  deps = [
    ':movies-lib',
  ],
)

android_library(
  name = 'movies-lib',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    react_native_target('java/com/facebook/csslayout:csslayout'),
    react_native_target('java/com/facebook/react:react'),
    react_native_target('java/com/facebook/react/devsupport:devsupport'),
    react_native_target('java/com/facebook/react/modules/core:core'),
    react_native_target('java/com/facebook/react/shell:shell'),
    react_native_target('java/com/facebook/react/touch:touch'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_target('java/com/facebook/react/uimanager/annotations:annotations'),
    react_native_target('java/com/facebook/react/views/image:image'),
    react_native_target('java/com/facebook/react/views/recyclerview:recyclerview'),
    react_native_target('java/com/facebook/react/views/scroll:scroll'),
    react_native_target('java/com/facebook/react/views/text:text'),
    react_native_target('java/com/facebook/react/views/view:view'),
    # .so files are prebuilt by Gradle with `./gradlew :ReactAndroid:packageReactNdkLibsForBuck`
    react_native_target('jni/prebuilt:reactnative-libs'),
    react_native_target('jni/prebuilt:android-jsc'),
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    ':res',
  ],
)


android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.facebook.react.movies',
)
