include_defs('//ReactAndroid/DEFS')

# Temp workaround to get the build working e2e, Gradle builds them for us

prebuilt_native_library(
  name = 'reactnative-libs',
  native_libs = 'lib',
  visibility = ['PUBLIC'],
)


android_prebuilt_aar(
  name = 'android-jsc',
  aar = ':android-jsc-aar',
  visibility = ['PUBLIC'],
)

remote_file(
  name = 'android-jsc-aar',
  url = 'mvn:org.webkit:android-jsc:aar:r174650',
  sha1 = '880cedd93f43e0fc841f01f2fa185a63d9230f85',
)
