load("//tools/build_defs/oss:rn_defs.bzl", "rn_android_library")

rn_android_library(
    name = "model",
    autoglob = False,
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        "//packages/annotations-compiler/annotations/src/main/java/com/facebook/react/module/model:model",
    ],
)
