include_defs('//ReactAndroid/DEFS')

android_binary(
  name = 'app',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//keystores:debug',
  deps = [
    ':uiexplorer-lib',
  ],
)

android_library(
  name = 'uiexplorer-lib',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    react_native_target('java/com/facebook/react:react'),
    react_native_target('java/com/facebook/react/modules/core:core'),
    react_native_target('java/com/facebook/react/shell:shell'),
    # .so files are prebuilt by Gradle with `./gradlew :ReactAndroid:packageReactNdkLibsForBuck`
    react_native_target('jni/prebuilt:reactnative-libs'),
    react_native_target('jni/prebuilt:android-jsc'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    ':res',
  ],
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.facebook.react.uiapp',
)
