load("//ReactNative:DEFS.bzl", "react_native_dep", "rn_android_library")

rn_android_library(
    name = "logging",
    exported_deps = [
        react_native_dep("libraries/fresco/fresco-react-native:fbcore"),
    ],
    visibility = ["//ReactAndroid/..."],
)
