load("//tools/build_defs/oss:rn_defs.bzl", "rn_java_annotation_processor")

rn_java_annotation_processor(
    name = "processing",
    does_not_affect_abi = True,
    processor_class = "com.facebook.react.module.processing.ReactModuleSpecProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//packages/annotations-compiler/compiler/src/main/java/com/facebook/react/module/processing:processing-lib",
    ],
)
