include_defs('//ReactAndroid/DEFS')

# used by ReactToolbarManager because of Gradle
# TODO t10182713 will be replaced with res-for-appcompat when we stop using Gradle
android_resource(
  name = 'res-for-react-native',
  res = react_native_dep('third-party/android/support/v7/appcompat-orig:res-unpacker-cmd'),
  package = 'com.facebook.react',
  visibility = ['//ReactAndroid/...',],
)
