include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'tests',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_integration_tests_target('java/com/facebook/react/testing:testing'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':tests',
)
