load("//tools/build_defs/oss:rn_defs.bzl", "react_native_target", "rn_android_library")

rn_android_library(
    name = "appregistry",
    srcs = glob(["**/*.java"]),
    autoglob = False,
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_target("java/com/facebook/react/bridge:bridge"),
    ],
)
