include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'appregistry',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_target('java/com/facebook/react/bridge:bridge'),
  ],
  visibility = [
    'PUBLIC',
  ],
)
