include_defs("//ReactAndroid/DEFS")

android_library(
    name = "systeminfo",
    srcs = [
        "AndroidInfoModule.java",
        "ReactNativeVersion.java",
    ],
    exported_deps = [
        ":systeminfo-moduleless",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
    ],
)

android_library(
    name = "systeminfo-moduleless",
    srcs = [
        "AndroidInfoHelpers.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)
