load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_target", "rn_android_library")

rn_android_library(
    name = "systeminfo",
    srcs = [
        "AndroidInfoModule.java",
        "ReactNativeVersion.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/module/annotations:annotations"),
        react_native_target("res:systeminfo"),
    ],
    exported_deps = [
        ":systeminfo-moduleless",
    ],
)

rn_android_library(
    name = "systeminfo-moduleless",
    srcs = [
        "AndroidInfoHelpers.java",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_target("java/com/facebook/react/common:common"),
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("res:systeminfo"),
    ],
)
