include_defs("//ReactAndroid/DEFS")

android_library(
    name = "slider",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        YOGA_TARGET,
        react_native_dep("android_res/com/facebook/catalyst/appcompat:appcompat"),
        react_native_dep("third-party/android/support/v7/appcompat-orig:appcompat"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/uimanager:uimanager"),
        react_native_target("java/com/facebook/react/uimanager/annotations:annotations"),
    ],
)
