
COPYFILES_PASS0_SRCROOT = $(OPENSOURCE_REACTNATIVE)\OfficeISS

COPYFILES_PASS0_DESTROOT = $(TARGETDIR)\include

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	Folly\folly\ApplyTuple.h, folly; \
	Folly\folly\Array.h, folly; \
	Folly\folly\Assume.h, folly; \
	Folly\folly\Baton.h, folly; \
	Folly\folly\Bits.h, folly; \
	Folly\folly\Conv.h, folly; \
	Folly\folly\CPortability.h, folly; \
	Folly\folly\CpuId.h, folly; \
	Folly\folly\Demangle.h, folly; \
	Folly\folly\detail\BitIteratorDetail.h, folly\detail; \
	Folly\folly\detail\BitsDetail.h, folly\detail; \
	Folly\folly\detail\Malloc.h, folly\detail; \
	Folly\folly\detail\RangeCommon.h, folly\detail; \
	Folly\folly\detail\RangeSse42.h, folly\detail; \
	Folly\folly\detail\UncaughtExceptionCounter.h, folly\detail; \
	Folly\folly\dynamic.h, folly; \
	Folly\folly\dynamic-inl.h, folly; \
	Folly\folly\Exception.h, folly; \
	Folly\folly\ExceptionString.h, folly; \
	Folly\folly\Expected.h, folly; \
	Folly\folly\FBString.h, folly; \
	Folly\folly\FBVector.h, folly; \
	Folly\folly\Format.h, folly; \
	Folly\folly\FormatArg.h, folly; \
	Folly\folly\Format-inl.h, folly; \
	Folly\folly\FormatTraits.h, folly; \
	Folly\folly\Hash.h, folly; \
	Folly\folly\json.h, folly; \
	Folly\folly\Likely.h, folly; \
	Folly\folly\Malloc.h, folly; \
	Folly\folly\Memory.h, folly; \
	Folly\folly\Optional.h, folly; \
	Folly\folly\Portability.h, folly; \
	Folly\folly\portability\BitsFunctexcept.h, folly\portability; \
	Folly\folly\portability\Builtins.h, folly\portability; \
	Folly\folly\portability\Config.h, folly\portability; \
	Folly\folly\portability\Constexpr.h, folly\portability; \
	Folly\folly\portability\Math.h, folly\portability; \
	Folly\folly\portability\String.h, folly\portability; \
	Folly\folly\portability\Windows.h, folly\portability; \
	Folly\folly\Preprocessor.h, folly; \
	Folly\folly\Range.h, folly; \
	Folly\folly\ScopeGuard.h, folly; \
	Folly\folly\SpookyHashV1.h, folly; \
	Folly\folly\SpookyHashV2.h, folly; \
	Folly\folly\String.h, folly; \
	Folly\folly\String-inl.h, folly; \
	Folly\folly\Traits.h, folly; \
	Folly\folly\UncaughtExceptions.h, folly; \
	Folly\folly\Unit.h, folly; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	ReactCommon\cxxreact\CxxModule.h, cxxreact; \
	ReactCommon\cxxreact\CxxNativeModule.h, cxxreact; \
	ReactCommon\cxxreact\Instance.h, cxxreact; \
	ReactCommon\cxxreact\JsArgumentHelpers.h, cxxreact; \
	ReactCommon\cxxreact\JsArgumentHelpers-inl.h, cxxreact; \
	ReactCommon\cxxreact\JSBigString.h, cxxreact; \
	ReactCommon\cxxreact\JSExecutor.h, cxxreact; \
	ReactCommon\cxxreact\MessageQueueThread.h, cxxreact; \
	ReactCommon\cxxreact\ModuleRegistry.h, cxxreact; \
	ReactCommon\cxxreact\NativeToJsBridge.h, cxxreact; \
	ReactCommon\cxxreact\NativeModule.h, cxxreact; \
	ReactCommon\cxxreact\PlatformBundleInfo.h, cxxreact; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	ReactCommon\privatedata\PrivateDataBase.h, privatedata; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	double-conversion\double-conversion\double-conversion.h, double-conversion; \
	double-conversion\double-conversion\utils.h, double-conversion; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	glog\src\windows\config.h, glog; \
	glog\src\windows\glog\logging.h, glog; \
	glog\src\windows\glog\raw_logging.h, glog; \
	glog\src\windows\glog\stl_logging.h, glog; \
	glog\src\windows\glog\vlog_is_on.h, glog; \
	glog\src\windows\glog\log_severity.h, glog; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	ReactAndroid\includes\msoFolly\msoFolly.h, msoFolly; \

COPYFILES_PASS0 = \
	$(COPYFILES_PASS0) \
	jsc\jsc-headers\JavaScript.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSBase.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSContextRef.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSObjectRef.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSStringRef.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSTypedArray.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\JSValueRef.h, jsc\JavaScriptCore; \
	jsc\jsc-headers\WebKitAvailability.h, jsc\JavaScriptCore; \

