android_library(
  name = 'quicklog',
  srcs = glob(['*.java']),
  exported_deps = [
    '//java/com/facebook/quicklog/identifiers:identifiers',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':quicklog',
)
