load("//ReactNative:DEFS.bzl", "react_native_dep", "rn_android_library")

rn_android_library(
    name = "configuration",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/mockito:mockito"),
    ],
)
