# BUILD FILE SYNTAX: SKYLARK
load(
    "//tools/build_defs/oss:rn_defs.bzl",
    "IS_OSS_BUILD",
    "react_native_dep",
    "react_native_integration_tests_target",
    "react_native_target",
    "rn_android_library",
)

rn_android_library(
    name = "core",
    srcs = glob(["*.java"]),
    deps = ([
        react_native_dep("third-party/java/espresso:espresso"),
        react_native_dep("third-party/java/fest:fest"),
        react_native_dep("third-party/java/junit:junit"),
        react_native_dep("third-party/java/testing-support-lib:testing-support-lib"),
        react_native_integration_tests_target("java/com/facebook/react/testing:testing"),
        react_native_integration_tests_target("java/com/facebook/react/testing/rule:rule"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/shell:shell"),
        react_native_target("java/com/facebook/react/uimanager:uimanager"),
    ]) + ([
        react_native_dep("java/com/facebook/fbreact/testing:testing"),
    ]) if not IS_OSS_BUILD else [],
)
