load("//ReactNative:DEFS.bzl", "rn_android_library", "react_native_dep")

rn_android_library(
    name = "network",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okio:okio"),
    ],
)
