android_prebuilt_aar(
    name = "soloader",
    aar = ":soloader-binary-aar",
    visibility = ["PUBLIC"],
)

remote_file(
    name = "soloader-binary-aar",
    sha1 = "042357559a6c9313bdb9b1ba137a9df3b5365f35",
    url = "mvn:com.facebook.soloader:soloader:aar:0.5.1",
)
