/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * <p>This source code is licensed under the MIT license found in the LICENSE file in the root
 * directory of this source tree.
 *
 * <p>Generated by an internal genrule from Flow types.
 *
 * @generated
 * @nolint
 */

package com.facebook.fbreact.specs;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;

public abstract class NativeDevSettingsSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {
  public NativeDevSettingsSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @ReactMethod
  public abstract void setIsDebuggingRemotely(boolean isDebuggingRemotelyEnabled);

  @ReactMethod
  public void onFastRefresh() {
  }

  @ReactMethod
  public abstract void removeListeners(double count);

  @ReactMethod
  public abstract void reload();

  @ReactMethod
  public abstract void setProfilingEnabled(boolean isProfilingEnabled);

  @ReactMethod
  public abstract void addMenuItem(String title);

  @ReactMethod
  public abstract void toggleElementInspector();

  @ReactMethod
  public abstract void setHotLoadingEnabled(boolean isHotLoadingEnabled);

  @ReactMethod
  public void reloadWithReason(String reason) {
  }

  @ReactMethod
  public abstract void setIsShakeToShowDevMenuEnabled(boolean enabled);

  @ReactMethod
  public abstract void addListener(String eventName);
}
