name: build-hermesc-apple
description: This action builds hermesc for Apple platforms
inputs:
  hermes-version:
    required: true
    description: The version of Hermes
  react-native-version:
    required: true
    description: The version of React Native
runs:
  using: composite
  steps:
    - name: Setup xcode
      uses: ./.github/actions/setup-xcode
    - name: Restore Hermes workspace
      uses: ./.github/actions/restore-hermes-workspace
    - name: Hermes apple cache
      uses: actions/cache/restore@v4
      with:
        path: ./packages/react-native/sdks/hermes/build_host_hermesc
        key: v2-hermesc-apple-${{ inputs.hermes-version }}-${{ inputs.react-native-version }}
    - name: Build HermesC Apple
      shell: bash
      run: |
        cd ./packages/react-native/sdks/hermes || exit 1
        . ./utils/build-apple-framework.sh
        build_host_hermesc_if_needed
    - name: Upload HermesC Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: hermesc-apple
        path: ./packages/react-native/sdks/hermes/build_host_hermesc
    - name: Cache hermesc apple
      uses: actions/cache/save@v4
      if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, '-stable') }} # To avoid that the cache explode.
      with:
        path: ./packages/react-native/sdks/hermes/build_host_hermesc
        key: v2-hermesc-apple-${{ inputs.hermes-version }}-${{ inputs.react-native-version }}
        enableCrossOsArchive: true
