load(
    "//tools/build_defs/oss:rn_defs.bzl",
    "APPLE",
    "get_apple_compiler_flags",
    "get_apple_inspector_flags",
    "get_preprocessor_flags_for_build_mode",
    "react_native_xplat_target",
    "rn_xplat_cxx_library",
    "subdir_glob",
)

APPLE_COMPILER_FLAGS = get_apple_compiler_flags()

rn_xplat_cxx_library(
    name = "safeareaview",
    srcs = glob(
        ["**/*.cpp"],
    ),
    headers = [],
    header_namespace = "",
    exported_headers = subdir_glob(
        [
            ("", "*.h"),
        ],
        prefix = "react/renderer/components/safeareaview",
    ),
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-std=c++17",
        "-Wall",
    ],
    fbobjc_compiler_flags = APPLE_COMPILER_FLAGS,
    fbobjc_preprocessor_flags = get_preprocessor_flags_for_build_mode() + get_apple_inspector_flags(),
    force_static = True,
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    platforms = APPLE,
    preprocessor_flags = [
        "-DLOG_TAG=\"ReactNative\"",
        "-DWITH_FBSYSTRACE=1",
    ],
    visibility = ["PUBLIC"],
    deps = [
        react_native_xplat_target("react/debug:debug"),
        react_native_xplat_target("react/renderer/core:core"),
        "//xplat/js/react-native-github:generated_components-rncore",
    ],
)
