require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'HelloWorld-macOS' do
  platform :macos, '10.13'
  use_native_modules!
  use_react_native!(:path => '../node_modules/react-native-macos')

  # Enables Hermes
  #
  # Be sure to first install the `hermes-engine-darwin` npm package, e.g.:
  #
  #   $ yarn add 'hermes-engine-darwin@~0.5.0'
  #
  # pod 'React-Core/Hermes', :path => '../node_modules/react-native-macos/'
  # pod 'hermes', :path => '../node_modules/hermes-engine-darwin'
  # pod 'libevent', :podspec => '../node_modules/react-native-macos/third-party-podspecs/libevent.podspec'

  # Pods specifically for macOS target
end

target 'HelloWorld-iOS' do
  platform :ios, '10'
  use_native_modules!
  use_react_native!(:path => '../node_modules/react-native-macos')

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  # Pods specifically for iOS target
end
