load(
    "//tools/build_defs/oss:rn_defs.bzl",
    "IS_OSS_BUILD",
    "react_native_dep",
    "react_native_integration_tests_target",
    "react_native_target",
    "rn_android_library",
)

rn_android_library(
    name = "rule",
    srcs = glob(["*.java"]),
    autoglob = False,
    language = "JAVA",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/android/androidx:test-espresso-core"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/junit:junit"),
        react_native_dep("third-party/android/androidx:annotation"),
        react_native_dep("third-party/android/androidx:appcompat"),
        react_native_dep("third-party/android/androidx:core"),
        react_native_dep("third-party/android/androidx:fragment"),
        react_native_dep("third-party/android/androidx:legacy-support-core-utils"),
        react_native_dep("third-party/android/androidx:test-rules"),
        react_native_dep("third-party/android/androidx:test-runner"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_integration_tests_target("java/com/facebook/react/testing:testing"),
        react_native_integration_tests_target("java/com/facebook/react/testing/idledetection:idledetection"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/modules/core:core"),
        react_native_target("java/com/facebook/react/shell:shell"),
        react_native_target("java/com/facebook/react/uimanager:uimanager"),
    ] + [
        react_native_dep("java/com/facebook/testing/instrumentation:instrumentation"),
        react_native_dep("java/com/facebook/testing/instrumentation/base:base"),
    ] if not IS_OSS_BUILD else [],
)
