all:
	NODE_PATH="../../../../node_modules/" babel --presets babel-preset-react-native -d out src

watch:
	NODE_PATH="../../../../node_modules/" babel --watch --presets babel-preset-react-native -d out src
