include_defs('//ReactAndroid/DEFS')

# We are running instrumentation tests in simple mode: app code and instrumentation are in the samle APK
# Currently you need to run thesse commands to make them run:
#
# node local-cli/cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/assets/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
# gradle :ReactAndroid:packageReactNdkLibsForBuck
# buck install ReactAndroid/src/androidTest/buck-runner:react-instrumentation-tests-binary
# adb shell am instrument -w com.facebook.react.tests/android.support.test.runner.AndroidJUnitRunner
android_binary(
  name = 'react-instrumentation-tests-binary',
  manifest = 'AndroidManifest.xml',
  keystore = '//keystores:debug',
  deps = [
    react_native_integration_tests_target('java/com/facebook/react/tests:tests'),
    react_native_integration_tests_target('assets:assets'),
    react_native_target('jni/prebuilt:reactnative-libs'),
    react_native_target('jni/prebuilt:android-jsc'),
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
    react_native_target('java/com/facebook/react/devsupport:devsupport'),
  ],
)

