include_defs('//ReactAndroid/DEFS')


android_instrumentation_test(
  name = 'react-oss-tests',
  apk = ':react-oss-test-apk',
)

android_instrumentation_apk(
  name = 'react-oss-test-apk',
  manifest = 'AndroidManifest.xml',
  apk = ':react-instrumentation-tests-binary',
  deps = [
    react_native_integration_tests_target('java/com/facebook/react/tests:tests'),
  ],
)

# node local-cli/cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/assets/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
# gradle :ReactAndroid:packageReactNdkLibsForBuck
# buck install ReactAndroid/src/androidTest/buck-runner:react-instrumentation-tests-binary
# adb shell am instrument -w com.facebook.react.tests/android.support.test.runner.AndroidJUnitRunner
android_binary(
  name = 'react-instrumentation-tests-binary',
  manifest = 'AndroidManifest.xml',
  keystore = '//keystores:debug',
  deps = [
    react_native_integration_tests_target('java/com/facebook/react/tests:tests'),
    react_native_integration_tests_target('assets:assets'),
    react_native_target('jni/prebuilt:reactnative-libs'),
    react_native_target('jni/prebuilt:android-jsc'),
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
    react_native_target('java/com/facebook/react/devsupport:devsupport'),
  ],
)

