load("//tools/build_defs/oss:rn_defs.bzl", "rn_android_library", "react_native_dep", "rn_xplat_cxx_library")

rn_android_library(
    name = "instrumentation",
    srcs = ["HermesMemoryDumper.java"],
    visibility = ["PUBLIC"],
    deps = [
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
    ],
)

rn_android_library(
    name = "impl",
    srcs = ["HermesMemoryDumperImpl.java"],
    visibility = ["PUBLIC"],
    deps = [
        react_native_dep("java/com/facebook/common/appstate:appstate"),
        react_native_dep("java/com/facebook/common/errorreporting/memory:memory"),
        react_native_dep("java/com/facebook/common/fileupload:fileupload"),
        react_native_dep("java/com/facebook/common/identifiers:identifiers"),
        react_native_dep("java/com/facebook/common/stringformat:stringformat"),
        react_native_dep("java/com/facebook/common/time:time"),
        react_native_dep("java/com/facebook/hermes/annotations:annotations"),
        react_native_dep("java/com/facebook/inject:inject"),
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        ":instrumentation",
    ],
)

rn_xplat_cxx_library(
    name = "jni-interface",
    srcs = [],
    header_namespace = "hermes/jni/instrumentation",
    exported_headers = ["HermesMemoryDumper.h"],
    visibility = ["PUBLIC"],
    deps = [
        react_native_dep("native/fb:fb"),
    ],
)
