/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#ifdef REACT_NATIVE_HAS_SERIALIZABLE_STATE
#include <folly/dynamic.h>
#endif

namespace facebook::react {

class SampleNativeComponentState {
public:
  SampleNativeComponentState() = default;

#ifdef REACT_NATIVE_HAS_SERIALIZABLE_STATE
  SampleNativeComponentState(SampleNativeComponentState const &previousState, folly::dynamic data){};
  folly::dynamic getDynamic() const {
    return {};
  };
#endif
};

} // namespace facebook::react
