include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'csslayout',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_dep('third-party/java/infer-annotations:infer-annotations'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
  ],
  visibility = ['PUBLIC'],
)

project_config(
  src_target = ':csslayout',
)
