load("//tools/build_defs/oss:rn_defs.bzl", "ANDROID", "APPLE", "CXX", "react_native_xplat_shared_library_target", "react_native_xplat_target", "rn_xplat_cxx_library")

rn_xplat_cxx_library(
    name = "bridging",
    srcs = glob(["*.cpp"]),
    header_namespace = "react/bridging",
    exported_headers = glob(["*.h"]),
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    platforms = (ANDROID, APPLE, CXX),
    visibility = ["PUBLIC"],
    deps = [
        "//xplat/folly:headers_only",
    ],
    exported_deps = [
        react_native_xplat_target("butter:butter"),
        react_native_xplat_target("callinvoker:callinvoker"),
        react_native_xplat_shared_library_target("jsi:jsi"),
    ],
)
