include_defs("//ReactAndroid/DEFS")

android_binary(
    name = "app",
    keystore = "//keystores:debug",
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        ":rntester-lib",
    ],
)

android_library(
    name = "rntester-lib",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [
        ":res",
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/android/support/v7/appcompat-orig:appcompat"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/modules/core:core"),
        react_native_target("java/com/facebook/react/shell:shell"),
        react_native_target("jni/prebuilt:android-jsc"),
        # .so files are prebuilt by Gradle with `./gradlew :ReactAndroid:packageReactNdkLibsForBuck`
        react_native_target("jni/prebuilt:reactnative-libs"),
    ],
)

android_resource(
    name = "res",
    package = "com.facebook.react.uiapp",
    res = "src/main/res",
)
