load("//tools/build_defs/oss:rn_defs.bzl", "KEYSTORE_TARGET", "react_native_dep", "react_native_target", "rn_android_binary", "rn_android_library", "rn_android_resource")

rn_android_binary(
    name = "app",
    keystore = KEYSTORE_TARGET,
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        ":rntester-lib",
    ],
)

rn_android_library(
    name = "rntester-lib",
    srcs = glob(["src/main/java/**/*.java"]),
    is_androidx = True,
    deps = [
        ":res",
        react_native_dep("third-party/android/androidx:annotation"),
        react_native_dep("third-party/android/androidx:appcompat"),
        react_native_dep("third-party/android/androidx:core"),
        react_native_dep("third-party/android/androidx:fragment"),
        react_native_dep("third-party/android/androidx:legacy-support-core-ui"),
        react_native_dep("third-party/android/androidx:legacy-support-core-utils"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/common:build_config"),
        react_native_target("java/com/facebook/react/modules/core:core"),
        react_native_target("java/com/facebook/react/shell:shell"),
        react_native_target("jni/prebuilt:android-jsc"),
        # .so files are prebuilt by Gradle with `./gradlew :ReactAndroid:packageReactNdkLibsForBuck`
        react_native_target("jni/prebuilt:reactnative-libs"),
    ],
)

rn_android_resource(
    name = "res",
    package = "com.facebook.react.uiapp",
    res = "src/main/res",
)
