load("//ReactNative:DEFS.bzl", "rn_android_library", "react_native_dep")

rn_android_library(
    name = "holder",
    srcs = glob(["*.java"]),
    exported_deps = [
        react_native_dep("java/com/facebook/debug/debugoverlay/model:model"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)
