name: lint
description: Runs all the linters in the codebase
inputs:
  node-version:
    description: "The node.js version to use"
    required: false
    default: "18"
  github-token:
    description: "The GitHub token used by pull-bot"
    required: true
runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
    - name: Yarn install
      shell: bash
      run: yarn install --non-interactive --frozen-lockfile
    - name: Run linters against modified files (analysis-bot)
      shell: bash
      run: yarn lint-ci
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Lint code
      shell: bash
      run: ./scripts/circleci/exec_swallow_error.sh yarn lint --format junit -o ./reports/junit/eslint/results.xml
    - name: Lint java
      shell: bash
      run: ./scripts/circleci/exec_swallow_error.sh yarn lint-java --check
    - name: Run flowcheck
      shell: bash
      run: yarn flow-check
    - name: Run typescript check
      shell: bash
      run: yarn test-typescript
    - name: Check license
      shell: bash
      run: ./scripts/circleci/check_license.sh
    - name: Check formatting
      shell: bash
      run: yarn run format-check
