name: lint
description: Runs all the linters in the codebase
inputs:
  node-version:
    description: "The node.js version to use"
    required: false
    default: "22"
  github-token:
    description: "The GitHub token used by pull-bot"
    required: true
runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
    - name: Run yarn install
      uses: ./.github/actions/yarn-install
    - name: Run linters against modified files (analysis-bot)
      shell: bash
      run: yarn lint-ci
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_PR_NUMBER: ${{ github.event.number }}
    - name: Lint code
      shell: bash
      run: ./.github/workflow-scripts/exec_swallow_error.sh yarn lint --format junit -o ./reports/junit/eslint/results.xml
    - name: Lint java
      shell: bash
      run: ./.github/workflow-scripts/exec_swallow_error.sh yarn lint-java --check
    - name: Lint file structure
      shell: bash
      run: ./.github/workflow-scripts/lint_files.sh
    - name: Verify not committing repo after running build
      shell: bash
      run: yarn run build --validate
    - name: Run flowcheck
      shell: bash
      run: yarn flow-check
    - name: Run typescript check
      shell: bash
      run: yarn test-typescript
    - name: Check license
      shell: bash
      run: ./.github/workflow-scripts/check_license.sh
    - name: Check formatting
      shell: bash
      run: yarn run format-check
    - name: Lint markdown
      shell: bash
      run: yarn run lint-markdown
    - name: Build types
      shell: bash
      run: yarn build-types
    - name: Run typescript check of generated types
      shell: bash
      run: yarn test-generated-typescript
