include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'content',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_dep('libraries/fbcore/src/main/java/com/facebook/common/logging:logging'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/module/annotations:annotations'),
    react_native_target('java/com/facebook/react/modules/core:core'),
  ],
  visibility = [
    'PUBLIC',
  ],
)

