android_library(
  name = 'annotations',
  srcs = glob(['*.java']),
  proguard_config = 'proguard_annotations.pro',
  deps = [
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':annotations',
)
