include_defs("//ReactCommon/DEFS")

rn_xplat_cxx_library(
    name = "privatedata",
    srcs = glob(["**/*.cpp"]),
    header_namespace = "",
    exported_headers = subdir_glob(
        [
            ("", "**/*.h"),
        ],
        prefix = "privatedata",
    ),
    compiler_flags = [
        "-Wall",
        "-fexceptions",
        "-frtti",
        "-fvisibility=hidden",
        "-std=c++1y",
    ],
    visibility = [
        "PUBLIC",
    ],
)
