cxx_library(
  name = 'yoga',
  force_static = True,
  srcs = glob(['yoga/*.c']),
  header_namespace = '',
  compiler_flags = [
    '-fno-omit-frame-pointer',
    '-fexceptions',
    '-Wall',
    '-Werror',
    '-std=c99',
    '-O3',
  ],
  exported_headers = glob(['yoga/*.h']),
  deps = [
  ],
  visibility = ['PUBLIC'],
)
