#!/bin/sh

cp Pods/Headers/Private/Yoga/yoga/YGNode.h Pods/Headers/Public/Yoga/yoga/YGNode.h
cp Pods/Headers/Private/Yoga/yoga/YGStyle.h Pods/Headers/Public/Yoga/yoga/YGStyle.h
cp Pods/Headers/Private/React-Core/React/RCTFollyConvert.h Pods/Headers/Public/React-Core/React/RCTFollyConvert.h
touch Pods/Headers/Public/React-Fabric/FBRCTFabricComponentsPlugins.h
