platform :ios, '9.0'

require_relative '../scripts/autolink-ios'

def pods()
  # Uncomment for Swift
  # use_frameworks!

  project 'RNTesterPods.xcodeproj'

  # Enable TurboModule
  use_react_native!(path: "..", turbo_modules_enabled: true)
  pod 'React-turbomodule-samples', :path => '../ReactCommon/turbomodule/samples'

  # Additional Pods which aren't included in the default Podfile
  pod 'React-ART', :path => '../Libraries/ART'
  pod 'React-RCTPushNotification', :path => '../Libraries/PushNotificationIOS'

  # Additional Pods which are classed as unstable
  #
  # To use fabric: add `fabric_enabled` option to the use_react_native method above, like below
  # use_react_native!(path: "..", turbo_modules_enabled: true, fabric_enabled: true)
end

target 'RNTester' do
  pods()
end

target 'RNTesterUnitTests' do
  pods()
  pod 'React-RCTTest', :path => "RCTTest"
end

target 'RNTesterIntegrationTests' do
  pods()
  pod 'React-RCTTest', :path => "RCTTest"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
