require_relative '../scripts/react_native_pods'

source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

# TODO(macOS GH#214)
# Otherwise duplicate UUIDs are being generated between the iOS and macOS targets.
# FIXME: https://github.com/microsoft/react-native/issues/210
install! 'cocoapods', :deterministic_uuids => false

if ENV['USE_FRAMEWORKS'] == '1'
  puts "Installing pods with use_frameworks!"
  use_frameworks!
end

def pods(options = {})
  project 'RNTesterPods.xcodeproj'

  # Enable TurboModule
  use_react_native!(options.merge(path: ".."))
  pod 'ReactCommon/turbomodule/samples', :path => '../ReactCommon'

  # Additional Pods which aren't included in the default Podfile
  pod 'React-ART', :path => '../Libraries/ART'
  pod 'React-RCTPushNotification', :path => '../Libraries/PushNotificationIOS'
  pod 'Yoga',:path => '../ReactCommon/yoga', :modular_headers => true
  pod 'React-TurboModuleCxx-WinRTPort', :path => '../ReactTurboModuleCxx'
  pod 'React-TurboModuleCxx-RNW', :podspec => '../ReactTurboModuleCxx/React-TurboModuleCxx-RNW.podspec'
  # Additional Pods which are classed as unstable
  #
  # To use fabric: add `fabric_enabled` option to the use_react_native method above, like below
  # use_react_native!(path: "..", fabric_enabled: true)
end

target 'RNTester' do
  pods()
  use_flipper!
end

target 'RNTesterUnitTests' do
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

target 'RNTesterIntegrationTests' do
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

target 'RNTester-macOS' do
  platform :osx, '10.14'
  pods(:hermes_enabled => true)
end

target 'RNTester-macOSUnitTests' do
  platform :osx, '10.14'
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

target 'RNTester-macOSIntegrationTests' do
  platform :osx, '10.14'
  pods()
  pod 'React-RCTTest', :path => "./RCTTest"
end

# [TODO(macOS ISS#2323203): these are special targets used by the internal Microsoft build pipeline
target 'iosDeviceBuild' do
  platform :ios, '10.0'
  pods()
end

target 'iosSimulatorBuild' do
  platform :ios, '10.0'
  pods()
end

target 'macOSBuild' do
  platform :osx, '10.14'
  pods()
end
# ]TODO(macOS ISS#2323203)

post_install do |installer|
  flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    # [TODO(macOS ISS#2323203): the internal Microsoft build pipeline needs iOS arm64e slices
    if target.platform_name == :ios
      target.build_configurations.each do |config|
        (config.build_settings['ARCHS'] ||= ['$(ARCHS_STANDARD)']) << 'arm64e'
      end
    end
    # TODO(macOS ISS#2323203): the internal Microsoft build pipeline needs macOS arm64 slices
    if target.platform_name == :osx
      target.build_configurations.each do |config|
        (config.build_settings['ARCHS'] ||= ['$(ARCHS_STANDARD)']) << ' arm64'
      end
    end
    # ]TODO(macOS ISS#2323203)
  end
end
