include_defs("//ReactAndroid/DEFS")

android_resource(
    name = "devsupport",
    package = "com.facebook.react",
    res = "devsupport",
    visibility = [
        react_native_target("java/com/facebook/react/devsupport/..."),
    ],
)

android_resource(
    name = "shell",
    package = "com.facebook.react",
    res = "shell",
    visibility = [
        "PUBLIC",
    ],
)

android_resource(
    name = "modal",
    package = "com.facebook.react",
    res = "views/modal",
    visibility = [
        "PUBLIC",
    ],
)

android_resource(
    name = "uimanager",
    package = "com.facebook.react",
    res = "views/uimanager",
    visibility = [
        "PUBLIC",
    ],
)

# New resource directories must be added to react-native-github/ReactAndroid/build.gradle
