include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'soloader',
  srcs = glob(['*.java']),
  proguard_config = 'soloader.pro',
  deps = [
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    # Be very careful adding new dependencies here, because this code
    # has to run very early in the app startup process.
    # Definitely do *not* depend on lib-base or guava.
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':soloader',
)
