load("//ReactNative:DEFS.bzl", "YOGA_TARGET", "react_native_dep", "react_native_target", "react_native_tests_target", "rn_robolectric_test")

rn_robolectric_test(
    name = "uimanager",
    # TODO Disabled temporarily until Yoga linking is fixed t14964130
    # srcs = glob(['**/*.java']),
    srcs = [
        "MatrixMathHelperTest.java",
        "SimpleViewPropertyTest.java",
    ],
    # Please change the contact to the oncall of your team
    contacts = ["oncall+fbandroid_sheriff@xmail.facebook.com"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        YOGA_TARGET,
        react_native_dep("libraries/fbcore/src/test/java/com/facebook/powermock:powermock"),
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/java/fest:fest"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/junit:junit"),
        react_native_dep("third-party/java/mockito:mockito"),
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okio:okio"),
        react_native_dep("third-party/java/robolectric3/robolectric:robolectric"),
        react_native_target("java/com/facebook/react:react"),
        react_native_target("java/com/facebook/react/animation:animation"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/common:common"),
        react_native_target("java/com/facebook/react/touch:touch"),
        react_native_target("java/com/facebook/react/uimanager:uimanager"),
        react_native_target("java/com/facebook/react/uimanager/annotations:annotations"),
        react_native_target("java/com/facebook/react/views/text:text"),
        react_native_target("java/com/facebook/react/views/view:view"),
        react_native_tests_target("java/com/facebook/react/bridge:testhelpers"),
    ],
)
