name: Run Fantom Tests
runs:
  using: composite
  steps:
    - name: Install runtime dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y openssl libssl-dev
    - name: Setup git safe folders
      shell: bash
      run: git config --global --add safe.directory '*'
    - name: Setup node.js
      uses: ./.github/actions/setup-node
    - name: Install node dependencies
      uses: ./.github/actions/yarn-install
    - name: Download Fantom Runner binary
      uses: actions/download-artifact@v4
      with:
        name: fantom-runner-binary
        path: private/react-native-fantom/build/tester
    - name: Make binary executable
      shell: bash
      run: chmod +x private/react-native-fantom/build/tester/fantom_tester
    - name: Run Fantom Tests
      shell: bash
      run: yarn fantom
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4.3.4
      with:
        name: run-fantom-tests-results
        compression-level: 1
        path: |
          private/react-native-fantom/build/reports
