name: Run Fantom Tests
inputs:
  release-type:
    required: true
    description: The type of release we are building. It could be nightly, release or dry-run
  gradle-cache-encryption-key:
    description: "The encryption key needed to store the Gradle Configuration cache"

runs:
  using: composite
  steps:
    - name: Run Fantom Tests
      shell: bash
      run: yarn jest --config private/react-native-fantom/config/jest.config.js
      env:
        FANTOM_FORCE_OSS_BUILD: 1
        NODE_OPTIONS: '--max-old-space-size=8192'
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4.3.4
      with:
        name: run-fantom-tests-results
        compression-level: 1
        path: |
          private/react-native-fantom/build/reports
