load("//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

fb_native.android_library(
    name = "java",
    exported_deps = [
        ":fbjni-binary",
    ],
    visibility = ["PUBLIC"],
)

fb_native.android_prebuilt_aar(
    name = "fbjni-binary",
    aar = ":fbjni-binary-aar",
)

fb_native.remote_file(
    name = "fbjni-binary-aar",
    sha1 = "b20ae3406d911a28315b6ab53f122075500bfa27",
    url = "mvn:com.facebook.fbjni:fbjni:aar:0.2.2",
)
