load("//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

fb_native.android_library(
    name = "java",
    exported_deps = [
        ":fbjni-binary",
    ],
    visibility = ["PUBLIC"],
)

fb_native.android_prebuilt_aar(
    name = "fbjni-binary",
    aar = ":fbjni-binary-aar",
)

fb_native.remote_file(
    name = "fbjni-binary-aar",
    sha1 = "d9e1b6ebbe55fe25f6ee6257ef64588e0f8a8db0",
    url = "mvn:com.facebook.fbjni:fbjni:aar:0.0.2",
)
