
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <react/renderer/components/rncore/ShadowNodes.h>

namespace facebook {
namespace react {

extern const char ActivityIndicatorViewComponentName[] = "ActivityIndicatorView";
extern const char DatePickerComponentName[] = "DatePicker";
extern const char AndroidDrawerLayoutComponentName[] = "AndroidDrawerLayout";
extern const char RCTMaskedViewComponentName[] = "RCTMaskedView";
extern const char RCTProgressViewComponentName[] = "RCTProgressView";
extern const char AndroidSwipeRefreshLayoutComponentName[] = "AndroidSwipeRefreshLayout";
extern const char PullToRefreshViewComponentName[] = "PullToRefreshView";
extern const char RCTSegmentedControlComponentName[] = "RCTSegmentedControl";
extern const char SwitchComponentName[] = "Switch";
extern const char UnimplementedNativeViewComponentName[] = "UnimplementedNativeView";

} // namespace react
} // namespace facebook
