include_defs('//ReactAndroid/DEFS')

cxx_library(
  name = 'perftests',
  srcs = [ 'OnLoad.cpp' ],
  soname = 'libnativereactperftests.so',
  compiler_flags = [
    '-fexceptions',
  ],
  deps = [
    '//native/fb:fb',
    '//native:base',
    '//xplat/folly:molly',
    react_native_xplat_target('cxxreact:module'),
  ],
  visibility = [
    '//instrumentation_tests/com/facebook/react/...',
  ],
)

project_config(
  src_target = ':perftests',
)
