/**
* Copyright (c) Facebook, Inc. and its affiliates.
*
* This source code is licensed under the MIT license found in the
* LICENSE file in the root directory of this source tree.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableMap;

public interface SliderManagerInterface<T extends View> {
  void setDisabled(T view, boolean value);
  void setEnabled(T view, boolean value);
  void setMaximumTrackImage(T view, @Nullable ReadableMap value);
  void setMaximumTrackTintColor(T view, @Nullable Integer value);
  void setMaximumValue(T view, double value);
  void setMinimumTrackImage(T view, @Nullable ReadableMap value);
  void setMinimumTrackTintColor(T view, @Nullable Integer value);
  void setMinimumValue(T view, double value);
  void setStep(T view, double value);
  void setTestID(T view, @Nullable String value);
  void setThumbImage(T view, @Nullable ReadableMap value);
  void setThumbTintColor(T view, @Nullable Integer value);
  void setTrackImage(T view, @Nullable ReadableMap value);
  void setValue(T view, double value);
}
