include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'recyclerview',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/touch:touch'),
    react_native_target('java/com/facebook/react/uimanager:uimanager'),
    react_native_target('java/com/facebook/react/views/scroll:scroll'),
    react_native_target('java/com/facebook/react/views/view:view'),
    '//third-party/android-support-v7/recyclerview:recyclerview',
    '//third-party/java/android/support/v4:lib-support-v4',
    '//third-party/java/infer-annotations:infer-annotations',
    '//third-party/java/jsr-305:jsr-305',
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':recyclerview',
)
