include_defs("//ReactAndroid/DEFS")

android_library(
    name = "idledetection",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/testing-support-lib:runner"),
        react_native_target("java/com/facebook/react/bridge:bridge"),
        react_native_target("java/com/facebook/react/modules/core:core"),
    ],
)
