name: test-js
description: Runs all the JS tests in the codebase
inputs:
  node-version:
    description: "The node.js version to use"
    required: false
    default: "22"
runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
    - name: Yarn install
      uses: ./.github/actions/yarn-install
    - name: Run Tests - JavaScript Tests
      shell: bash
      run: node ./scripts/run-ci-javascript-tests.js --maxWorkers 2
    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4.3.4
      with:
        name: test-js-results
        compression-level: 1
        path: ./reports/junit
