load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library")

fb_apple_library(
    name = "FBLazyVector",
    exported_headers = [
        "FBLazyVector/FBLazyIterator.h",
        "FBLazyVector/FBLazyVector.h",
    ],
    autoglob = False,
    complete_nullability = True,
    contacts = ["oncall+react_native@xmail.facebook.com"],
    enable_exceptions = False,
    extension_api_only = True,
    frameworks = [],
    labels = ["supermodule:xplat/default/public.react_native.infra"],
    link_whole = False,
    visibility = ["PUBLIC"],
)
