load("//tools/build_defs/oss:rn_defs.bzl", "fb_apple_library")

fb_apple_library(
    name = "FBLazyVector",
    autoglob = True,
    contacts = ["oncall+react_native@xmail.facebook.com"],
    enable_exceptions = False,
	labels = ["supermodule:ios/isolation/infra.react_native"],
    frameworks = [],
    link_whole = False,
    visibility = ["PUBLIC"],
)
