include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'jni',
  srcs = glob(['**/*.java']),
  deps = [
    react_native_dep('java/com/facebook/proguard/annotations:annotations'),
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
  ],
  visibility = [
    'PUBLIC',
  ],
)

project_config(
  src_target = ':jni',
)
