include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'jni',
  srcs = glob(['**/*.java']),
  proguard_config = 'fbjni.pro',
  deps = [
    react_native_dep('java/com/facebook/proguard/annotations:annotations'),
    react_native_dep('libraries/soloader/java/com/facebook/soloader:soloader'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
  ],
  visibility = [
    'PUBLIC',
  ]
)

project_config(
  src_target = ':jni',
)
