# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: /.ado/variables/vars.yml@self

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

stages:
  - stage: Build_And_Test
    displayName: 'Build and Test'
    dependsOn: []
    jobs:
      - template: /.ado/jobs/build-test-rntester.yml@self

  - stage: JSOnly
    dependsOn: []
    jobs:
      - template: /.ado/jobs/test-javascript.yml@self

  # - stage: Integration
  #   dependsOn: []
  #   jobs:
      #- template: /.ado/jobs/test-react-native-macos-init.yml@self

      # - template: /.ado/jobs/react-native-test-app-integration.yml@self