# This file defines the Apple PR build steps used during the CI loop
name: $(Date:yyyyMMdd).$(Rev:.r)

variables:
  - template: variables/vars.yml

trigger: none # will disable CI builds entirely

pr:
  branches:
    include:
      - main
      - '*-stable'
  paths:
    exclude:
      - '*.md'

jobs:
  - job: JavaScriptPR
    displayName: Javascript PR
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/apple-job-javascript.yml
        parameters:
            slice_name: $(slice_name)
            xcode_version: $(xcode_version)

  - job: ApplePR
    displayName: PR
    strategy:
      matrix:
        'iOS Paper Debug JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build test'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
          use_fabric: '0'
          use_hermes: '0'
        'iOS Paper Release JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
          use_fabric: '0'
          use_hermes: '0'
        'macOS Paper Debug JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build test'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
          use_fabric: '0'
          use_hermes: '0'
        'macOS Paper Release JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
          use_fabric: '0'
          use_hermes: '0'
        'iOS Fabric Debug JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build test'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
          use_fabric: '1'
          use_hermes: '0'
        'iOS Fabric Release JSC':
          packager_platform: 'ios'
          xcode_sdk: iphonesimulator
          xcode_scheme: 'RNTester'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
          xcode_actions: 'build'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
          use_fabric: '1' 
          use_hermes: '0'
        'macOS Fabric Debug JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Debug'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build test'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
          use_fabric: '1'
          use_hermes: '0'
        'macOS Fabric Release JSC':
          packager_platform: 'macos'
          xcode_sdk: macosx
          xcode_scheme: 'RNTester-macOS'
          xcode_configuration: 'Release'
          xcode_destination: 'platform=macOS,arch=x86_64'
          xcode_actions: 'build'
          xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
          use_fabric: '1'
          use_hermes: '0'
        # Disable Hermes Jobs for now
        # 'iOS Paper Debug Hermes':
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_configuration: 'Debug'
        #   xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
        #   xcode_actions: 'build test'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
        #   use_fabric: '0'
        #   use_hermes: '1'
        # 'iOS Paper Release Hermes':
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
        #   xcode_actions: 'build'
        #   use_fabric: '0'
        #   use_hermes: '1'
        # 'macOS Paper Debug Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Debug'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build test'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
        #   use_fabric: '0'
        #   use_hermes: '1'
        # 'macOS Paper Release Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
        #   use_fabric: '0'
        #   use_hermes: '1'
        # 'iOS Fabric Debug Hermes': 
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_configuration: 'Debug'
        #   xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
        #   xcode_actions: 'build test'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
        #   use_fabric: '1'
        #   use_hermes: '1'
        # 'iOS Fabric Release Hermes': 
        #   packager_platform: 'ios'
        #   xcode_sdk: iphonesimulator
        #   xcode_scheme: 'RNTester'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=iOS Simulator,OS=latest,name=iPhone 14'
        #   xcode_actions: 'build'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
        #   use_fabric: '1' 
        #   use_hermes: '0'
        # 'macOS Fabric Debug Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Debug'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build test'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/debug_overrides.xcconfig' 
        #   use_fabric: '1'
        #   use_hermes: '1'
        # 'macOS Fabric Release Hermes':
        #   packager_platform: 'macos'
        #   xcode_sdk: macosx
        #   xcode_scheme: 'RNTester-macOS'
        #   xcode_configuration: 'Release'
        #   xcode_destination: 'platform=macOS,arch=x86_64'
        #   xcode_actions: 'build'
        #   xcode_extraArgs: '-xcconfig $(Build.Repository.LocalPath)/.ado/xcconfig/release_overrides.xcconfig' 
        #   use_fabric: '1'
        #   use_hermes: '1'
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    timeoutInMinutes: 90 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    steps:
      - template: templates/apple-job-react-native.yml
        parameters:
          packager_platform: $(packager_platform)
          xcode_sdk: $(xcode_sdk)
          xcode_configuration: $(xcode_configuration)
          xcode_scheme: $(xcode_scheme)
          xcode_actions: $(xcode_actions)
          xcode_destination: $(xcode_destination)
          slice_name: $(slice_name)
          xcode_version: $(xcode_version)
          xcode_extraArgs: $(xcode_extraArgs)

  - job: CliInit
    displayName: Verify react-native-macos-init
    strategy:
      matrix:
        MacDebug:
          configuration: Debug
    pool:
      vmImage: $(VmImageApple)
      demands: ['xcode', 'sh', 'npm']
    steps:
      - template: templates/react-native-macos-init.yml
        parameters:
          configuration: $(configuration)
