load("//ReactNative:DEFS.bzl", "react_native_dep")

java_library(
    name = "java",
    srcs = glob(["**/*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
    ],
)
