include_defs("//ReactAndroid/DEFS")

java_library(
    name = "java",
    srcs = glob(["**/*.java"]),
    visibility = ["PUBLIC"],
    deps = [
        "//java/com/facebook/proguard/annotations:annotations",
    ],
)
