load("//ReactNative:DEFS.bzl", "IS_OSS_BUILD", "rn_android_library", "react_native_dep", "react_native_target")

rn_android_library(
    name = "packagerconnection",
    srcs = glob(
        ["**/*.java"],
        excludes = ["SamplingProfilerPackagerMethod.java"] if IS_OSS_BUILD else [],
    ),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("java/com/facebook/jni:jni"),
        react_native_dep("java/com/facebook/proguard/annotations:annotations"),
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("libraries/soloader/java/com/facebook/soloader:soloader"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okio:okio"),
        react_native_target("java/com/facebook/react/modules/systeminfo:systeminfo-moduleless"),
    ] + ([react_native_target("jni/packagerconnection:jni")] if not IS_OSS_BUILD else []),
)
