include_defs("//ReactAndroid/DEFS")

android_library(
    name = "packagerconnection",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("libraries/fbcore/src/main/java/com/facebook/common/logging:logging"),
        react_native_dep("third-party/java/infer-annotations:infer-annotations"),
        react_native_dep("third-party/java/jsr-305:jsr-305"),
        react_native_dep("third-party/java/okhttp:okhttp3"),
        react_native_dep("third-party/java/okhttp:okhttp3-ws"),
        react_native_dep("third-party/java/okio:okio"),
        react_native_target("java/com/facebook/react/modules/systeminfo:systeminfo-moduleless"),
    ],
)
