include_defs("//ReactAndroid/DEFS")

android_library(
    name = "common",
    srcs = glob(["*.java"]),
    provided_deps = [
        react_native_dep("third-party/android/support/v4:lib-support-v4"),
        react_native_dep("third-party/android/support-annotations:android-support-annotations")
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
