include_defs('//ReactAndroid/DEFS')

android_library(
  name = 'devsupport',
  manifest = 'AndroidManifest.xml',
  srcs = glob(['**/*.java']),
  deps = [
    '//libraries/fbcore/src/main/java/com/facebook/common/logging:logging',
    react_native_target('res:devsupport'),
    react_native_target('java/com/facebook/react/bridge:bridge'),
    react_native_target('java/com/facebook/react/common:common'),
    react_native_target('java/com/facebook/react/modules/debug:debug'),
    react_native_dep('third-party/java/infer-annotations:infer-annotations'),
    react_native_dep('third-party/java/jsr-305:jsr-305'),
    react_native_dep('third-party/java/okhttp:okhttp'),
    react_native_dep('third-party/java/okio:okio'),
  ],
  visibility = [
    react_native_target('java/com/facebook/react/...'),
    '//instrumentation_tests/com/facebook/catalyst/...',
    '//java/com/facebook/catalyst/...',
    '//java/com/facebook/groups/treehouse/react/...',
    '//java/com/facebook/fbreact/...',
    '//javatests/com/facebook/catalyst/...',
    '//javatests/com/facebook/react/...',
  ],
)

project_config(
  src_target = ':devsupport',
)
