# This jobs runs every day 2 hours after the nightly job and its purpose is to report
# a failure in case the nightly failed to be published. We are going to hook this to an internal automation.
name: Check Nightlies

on:
  workflow_dispatch:
  # nightly build @ 4:15 AM UTC
  schedule:
    - cron: '15 4 * * *'

jobs:
  check-nightly:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check nightly
        run: |
          TODAY=$(date "+%Y%m%d")
          echo "Checking nightly for $TODAY"
          NIGHTLY="$(npm view react-native | grep $TODAY)"
          if [[ -z $NIGHTLY ]]; then
            echo 'Nightly job failed.'
            exit 1
          else
            echo 'Nightly Worked, All Good!'
          fi

  test-libraries:
    uses: ./.github/workflows/test-libraries-on-nightlies.yml
    needs: check-nightly
    secrets:
      discord_webhook_url: ${{ secrets.NIGHTLY_DISCORD_WEBHOOK }}
