name: Run Danger on PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'facebook/react-native'
    steps:
      - uses: actions/checkout@v4
      - name: Run Yarn Install on Root
        run: yarn install
        working-directory: .
      - name: Danger
        run: yarn danger ci --use-github-checks --failOnErrors
        working-directory: packages/react-native-bots
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.REACT_NATIVE_BOT_GITHUB_TOKEN }}
