name: Generate Changelog

on:
  workflow_call:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install dependencies
        uses: ./.github/actions/yarn-install
      - name: Configure Git
        shell: bash
        run: |
          git config --local user.email "bot@reactnative.dev"
          git config --local user.name "React Native Bot"
      - name: Generate Changelog
        uses: actions/github-script@v6
        with:
          script: |
            const {generateChangelog} = require('./.github/workflow-scripts/generateChangelog');
            const version = '${{ github.ref_name }}';
            await generateChangelog(version, '${{secrets.REACT_NATIVE_BOT_GITHUB_TOKEN}}');
