name: Prebuild iOS Dependencies

on:
  workflow_call: # this directive allow us to call this workflow from other workflows


jobs:
  build-rn-slice:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        flavor: ['Debug', 'Release']
        slice: [
          'ios',
          'ios-simulator',
          'mac-catalyst',
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cache if present
        id: restore-ios-slice
        uses: actions/cache/restore@v4
        with:
          path: packages/react-native/third-party/
          key: v2-ios-core-${{ matrix.slice }}-${{ matrix.flavor }}-${{ hashFiles('packages/react-native/Package.swift') }}
          enableCrossOsArchive: true
      - name: Setup node.js
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-node
      - name: Setup xcode
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        uses: ./.github/actions/setup-xcode
        with:
          xcode-version: '16.2.0'
      - name: Yarn Install
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        uses: ./.github/actions/yarn-install
      - name: Download Hermes
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v4
        with:
          name: hermes-darwin-bin-${{ matrix.flavor }}
          path: /tmp/hermes/hermes-runtime-darwin
      - name: Extract Hermes
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        shell: bash
        run: |
          HERMES_TARBALL_ARTIFACTS_DIR=/tmp/hermes/hermes-runtime-darwin
          if [ ! -d $HERMES_TARBALL_ARTIFACTS_DIR ]; then
            echo "Hermes tarball artifacts dir not present ($HERMES_TARBALL_ARTIFACTS_DIR)."
            exit 0
          fi

          TARBALL_FILENAME=$(node ./packages/react-native/scripts/hermes/get-tarball-name.js --buildType "${{ matrix.flavor }}")
          TARBALL_PATH=$HERMES_TARBALL_ARTIFACTS_DIR/$TARBALL_FILENAME

          echo "Looking for $TARBALL_FILENAME in $HERMES_TARBALL_ARTIFACTS_DIR"
          echo "$TARBALL_PATH"

          if [ ! -f $TARBALL_PATH ]; then
            echo "Hermes tarball not present ($TARBALL_PATH). Build Hermes from source."
            exit 0
          fi

          echo "Found Hermes tarball at $TARBALL_PATH"
          echo "HERMES_ENGINE_TARBALL_PATH=$TARBALL_PATH" >> $GITHUB_ENV
      - name: Download ReactNativeDependencies
        uses: actions/download-artifact@v4
        with:
          name: ReactNativeDependencies${{ matrix.flavor }}.xcframework.tar.gz
          path: /tmp/third-party/
      - name: Extract ReactNativeDependencies
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # Extract ReactNativeDependencies
          tar -xzf /tmp/third-party/ReactNativeDependencies${{ matrix.flavor }}.xcframework.tar.gz -C /tmp/third-party/

          # Create destination folder
          mkdir -p packages/react-native/third-party/

          # Move the XCFramework in the destination directory
          mv /tmp/third-party/packages/react-native/third-party/ReactNativeDependencies.xcframework packages/react-native/third-party/ReactNativeDependencies.xcframework

          VERSION=$(jq -r '.version' package.json)
          echo "$VERSION-${{matrix.flavor}}" > "packages/react-native/third-party/version.txt"
          cat "packages/react-native/third-party/version.txt"
          # Check destination directory
          ls -lR packages/react-native/third-party/
      - name: Setup the workspace
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd packages/react-native
          node scripts/ios-prebuild.js ${{matrix.flavor}}
      - name: Build React Native
        if: steps.restore-ios-slice.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # This is going to be replaced by a CLI script
          cd packages/react-native
          DESTINATION="generic/platform=iOS simulator"
          if [ "${{ matrix.slice }}" == "ios" ]; then
            DESTINATION="generic/platform=iOS"
          elif [ "${{ matrix.slice }}" == "mac-catalyst" ]; then
            DESTINATION="generic/platform=macOS,variant=Mac Catalyst"
          fi
          xcodebuild -scheme React -destination "$DESTINATION" -derivedDataPath ./.build/output -configuration "${{ matrix.flavor }}" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: prebuild-ios-core-slice-${{ matrix.flavor }}-${{ matrix.slice }}
          path: |
            packages/react-native/.build/output/Build/Products
      - name: Save Cache
        uses: actions/cache/save@v4
        if: ${{ github.ref == 'refs/heads/main' }} # To avoid that the cache explode
        with:
          key: v2-ios-core-${{ matrix.slice }}-${{ matrix.flavor }}-${{ hashFiles('packages/react-native/Package.swift') }}
          enableCrossOsArchive: true
          path: |
            packages/react-native/.build/output/Build/Products
